In [1]:
import pandas as pd
import sys
import matplotlib.pyplot as plt
pd.options.display.max_columns=1000
pd.options.display.max_rows=1000
pd.set_option('display.max_colwidth', -1)
sys.path.insert(0, "C:\\Users\\vberlia\\Documents\\machine_learning")
import itertools

In [53]:
from machineLearning.dataSummary import DataSummary
from machineLearning.visualizations import Visualization
from machineLearning.ploty_visualization import PlotlyVisualization
import plotly.plotly as py
from machineLearning.missingValues import MissingValue
from machineLearning.models import Model
from machineLearning.modelInputs import KNNInputs
from machineLearning.pipelines import Pipelines
from machineLearning.featureCreation import CreateMeanLookupFeature
from machineLearning.featureCreation import CreateMedianLookupFeature
from machineLearning.featureCreation import CreateFrequencyLookupFeature
from machineLearning.featureCreation import CreateOneHotEncoding
from machineLearning.credit_prediction import classification_report
from machineLearning.featureCreation import CustomCutter
from machineLearning.credit_prediction import raw_features
from machineLearning.credit_prediction import create_features
from machineLearning.credit_prediction import prep_data
from machineLearning.featureCreation import IsMissingFeature
from sklearn import linear_model
from machineLearning.missingValues import CustomQuantitativeImputer
from machineLearning.misc import Misc
from machineLearning.missingValues import CustomEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import ggplot
from ggplot import *
import numpy as np

C:\Users\vberlia\AppData\Local\Continuum\Anaconda3\lib\site-packages\ggplot\utils.py:81: FutureWarning:

pandas.tslib is deprecated and will be removed in a future version.
You can access Timestamp as pandas.Timestamp

C:\Users\vberlia\AppData\Local\Continuum\Anaconda3\lib\site-packages\ggplot\stats\smoothers.py:4: FutureWarning:

The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead

C:\Users\vberlia\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning:

The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.

In [2]:
application_train=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/application_train.csv")
application_newData=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/application_test.csv")
# bureau=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/bureau.csv")
# bureau_balance=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/bureau_balance.csv")
# # credit_card_balance=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/credit_card_balance.csv")
home_credit_col_desc=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/HomeCredit_columns_description.csv",encoding = "ISO-8859-1")
# intall_payment=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/installments_payments.csv")
# pos_cash=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/POS_CASH_balance.csv")
# prev_app=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/previous_application.csv")
# sample_submi=pd.read_csv("C:/Users/vberlia/Documents/data/credit_prediction/all/sample_submission.csv")

In [304]:
miss_columns = raw_features.features.miss_columns
raw_columns = raw_features.features.raw_columns
freq_columns = raw_features.features.freq_columns
one_hot_columns = raw_features.features.one_hot_columns

In [305]:
set(application_train.columns)-(set(miss_columns)| set(raw_columns)| set(freq_columns)|set(one_hot_columns))

{'EMERGENCYSTATE_MODE',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'NAME_TYPE_SUITE',
 'SK_ID_CURR',
 'TARGET',
 'WALLSMATERIAL_MODE'}

In [325]:
from sklearn.base import TransformerMixin
class CustomCategoryImputer(TransformerMixin):
    def __init__(self, col=None,most_frequent=None):
        self.col = col
        self.most_frequent=most_frequent

    def transform(self, X, **transform_params):
        data = X.copy()       
        data[self.col]=data[self.col].fillna(self.most_frequent)
        return data

    def fit(self,X, y=None, **fit_params):
        self.most_frequent=X[self.col].value_counts().index[0]
        return self

In [388]:
tmp_removal=['EMERGENCYSTATE_MODE',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'NAME_TYPE_SUITE',
 'OCCUPATION_TYPE',
 'WALLSMATERIAL_MODE']

cols=['SK_ID_CURR','EMERGENCYSTATE_MODE_freq',
 'FONDKAPREMONT_MODE_freq',
 'HOUSETYPE_MODE_freq',
 'NAME_TYPE_SUITE_freq',
 'OCCUPATION_TYPE_freq',
 'WALLSMATERIAL_MODE_freq']

all_pipes = []

cat_miss_pipes = []
for col in tmp_removal:
    cat_miss_pipes.append(('miss_impute_'+col, CustomCategoryImputer(col=col)))

freq_pipes = []
for col in tmp_removal:
    freq_pipes.append(('freq_by_' + col, CreateFrequencyLookupFeature(categorical_column=col, new_col_name=
    col + '_freq')))    
    
all_pipes.append(Pipeline(cat_miss_pipes))
all_pipes.append(Pipeline(freq_pipes))

all_pipelines = []
count = 1
for pipe in all_pipes:
    all_pipelines.append(('feature_set' + str(count), pipe))
    count += 1
final_pipeline=Pipeline(all_pipelines)
final_pipeline.fit(application_train)
new_dat_train=final_pipeline.transform(application_train)[cols]
new_dat_new=final_pipeline.transform(application_newData)[cols]

In [30]:
all_loan_ids=pd.concat([application_train[['SK_ID_CURR']],
                        application_newData[['SK_ID_CURR']]])
all_loan_ids=all_loan_ids.reset_index()
all_loan_ids=all_loan_ids.drop('index',axis=1)

In [398]:
train_row_missing_count=pd.DataFrame(application_train.isnull().sum(axis=1))
train_row_missing_count.insert(0,'SK_ID_CURR',application_train['SK_ID_CURR'])
train_row_missing_count.columns=['SK_ID_CURR','miss_row_count']
train_row_missing_count['days_employed_negative']=(application_train['DAYS_EMPLOYED']<=0)*1
train_row_missing_count['days_empl_log']=np.log(np.abs(application_train['DAYS_EMPLOYED'])+1)
train_row_missing_count['amt_annuity_log']=np.log(np.abs(application_train['AMT_ANNUITY'])+1)
train_row_missing_count['amt_income_log']=np.log(np.abs(application_train['AMT_INCOME_TOTAL'])+1)
train_row_missing_count['amt_credit_log']=np.log(np.abs(application_train['AMT_CREDIT'])+1)
train_row_missing_count['amt_goods_price_log']=np.log(np.abs(application_train['AMT_GOODS_PRICE'])+1)
train_row_missing_count['amt_days_birth_log']=np.log(np.abs(application_train['DAYS_BIRTH'])+1)



new_row_missing_count=pd.DataFrame(application_newData.isnull().sum(axis=1))
new_row_missing_count.insert(0,'SK_ID_CURR',application_newData['SK_ID_CURR'])
new_row_missing_count.columns=['SK_ID_CURR','miss_row_count']
new_row_missing_count['days_employed_negative']=(application_newData['DAYS_EMPLOYED']<=0)*1
new_row_missing_count['days_empl_log']=np.log(np.abs(application_newData['DAYS_EMPLOYED'])+1)
new_row_missing_count['amt_annuity_log']=np.log(np.abs(application_newData['AMT_ANNUITY'])+1)
new_row_missing_count['amt_income_log']=np.log(np.abs(application_newData['AMT_INCOME_TOTAL'])+1)
new_row_missing_count['amt_credit_log']=np.log(np.abs(application_newData['AMT_CREDIT'])+1)
new_row_missing_count['amt_goods_price_log']=np.log(np.abs(application_newData['AMT_GOODS_PRICE'])+1)
new_row_missing_count['amt_days_birth_log']=np.log(np.abs(application_newData['DAYS_BIRTH'])+1)

# new_feats=pd.concat([train_row_missing_count,new_row_missing_count])
# new_feats=new_feats.reset_index()
# new_feats=new_feats.drop('index',axis=1)
# new_feats.columns=['SK_ID_CURR','miss_row_count','days_employed_negative','days_empl_log','amt_annuity_log','amt_income_log',
#                   'amt_credit_log','amt_goods_price_log','amt_days_birth_log']

In [399]:
new_dat_train=pd.merge(new_dat_train,train_row_missing_count,on='SK_ID_CURR',how='left')
new_dat_new=pd.merge(new_dat_new,new_row_missing_count,on='SK_ID_CURR',how='left')

new_feats=pd.concat([new_dat_train,new_dat_new])
new_feats=new_feats.reset_index()
new_feats=new_feats.drop('index',axis=1)

,SK_ID_CURR,miss_row_count,days_employed_negative,days_empl_log,amt_annuity_log,amt_income_log,amt_credit_log,amt_goods_price_log,amt_days_birth_log
0,100002,1,1,6.458338,10.114619,12.218500,12.915581,12.768544,9.155039
1,100003,2,1,7.080868,10.482892,12.506181,14.072865,13.937287,9.727108
2,100004,48,1,5.420535,8.817446,11.119898,11.813037,11.813037,9.854665
3,100006,56,1,8.019613,10.298481,11.813037,12.652947,12.601491,9.852510
4,100007,50,1,8.019284,9.992711,11.707678,13.148033,13.148033,9.900132

In [291]:
new_feats.head()

,SK_ID_CURR,miss_row_count,days_employed_negative,days_empl_log,amt_annuity_log,amt_income_log,amt_credit_log,amt_goods_price_log,amt_days_birth_log
0,100002,1,1,6.458338,10.114619,12.218500,12.915581,12.768544,9.155039
1,100003,2,1,7.080868,10.482892,12.506181,14.072865,13.937287,9.727108
2,100004,48,1,5.420535,8.817446,11.119898,11.813037,11.813037,9.854665
3,100006,56,1,8.019613,10.298481,11.813037,12.652947,12.601491,9.852510
4,100007,50,1,8.019284,9.992711,11.707678,13.148033,13.148033,9.900132

In [420]:
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.svm import SVC
import numpy as np
iris =  load_iris()
X = iris['data']
y = iris['target']
kmeans = KMeans(n_clusters=6).fit(X)
distances = np.column_stack([np.sum((X - center)**2, axis=1)**0.5 for center in kmeans.cluster_centers_])
svm = SVC().fit(distances, y)

In [431]:
svm.score(distances,y)

0.9466666666666667

In [432]:
svm = SVC().fit(X, y)
svm.score(X, y)

0.9866666666666667

In [433]:
a=pd.concat([pd.DataFrame(X),pd.DataFrame(distances)])

In [459]:
# Creating features based on the k-means clustering

cluster_cols=['EXT_SOURCE_3',
 'EXT_SOURCE_2',
 'EXT_SOURCE_1',
 'AMT_GOODS_PRICE',
 'AMT_ANNUITY',
 'REGION_POPULATION_RELATIVE',
 'DAYS_ID_PUBLISH']

cluster_train=application_train[cluster_cols]
cluster_new=application_newData[cluster_cols]

all_pipes = []
quant_miss_pipes = []
quant_miss_pipes.append(('miss_impute_cols', CustomQuantitativeImputer(cols=cluster_cols, strategy="median")))

all_pipes.append(Pipeline(quant_miss_pipes))

all_pipelines = []
count = 1
for pipe in all_pipes:
    all_pipelines.append(('feature_set' + str(count), pipe))
    count += 1
final_pipeline=Pipeline(all_pipelines)
final_pipeline.fit(cluster_train)

cluster_train=final_pipeline.transform(cluster_train)
cluster_new=final_pipeline.transform(cluster_new)

standardiser= StandardScaler()
standardiser.fit(cluster_train)
cluster_train=pd.DataFrame(standardiser.transform(cluster_train))
cluster_new=pd.DataFrame(standardiser.transform(cluster_new))
cluster_train.columns=cluster_cols
cluster_new.columns=cluster_cols

kmeans = KMeans(n_clusters=6).fit(cluster_train)

col_names=['cluster_'+str(i)+'_dist' for i in range(6)]
cluster_train_feats=pd.DataFrame(kmeans.transform(cluster_train))
cluster_train_feats.columns=col_names
cluster_new_feats=pd.DataFrame(kmeans.transform(cluster_new))
cluster_new_feats.columns=col_names

cluster_train_feats['sum_dist']=cluster_train_feats.sum(axis=1)
cluster_new_feats['sum_dist']=cluster_new_feats.sum(axis=1)

from itertools import combinations
comb_list=list(combinations(cluster_train_feats.columns, 2))
diff_cols=['diff_'+str(i) for i in range(len(comb_list))]
i=0
for comb in comb_list:
    cluster_train_feats[diff_cols[i]]=cluster_train_feats[comb[0]]-cluster_train_feats[comb[1]]
    cluster_new_feats[diff_cols[i]]=cluster_new_feats[comb[0]]-cluster_new_feats[comb[1]]
    i=i+1

In [467]:
standardiser= StandardScaler()
standardiser.fit(cluster_train)
cluster_train=pd.DataFrame(standardiser.transform(cluster_train))
cluster_new=pd.DataFrame(standardiser.transform(cluster_new))
cluster_train.columns=cluster_cols
cluster_new.columns=cluster_cols

In [461]:
application_train[cluster_cols].head()

,EXT_SOURCE_3,EXT_SOURCE_2,EXT_SOURCE_1,AMT_GOODS_PRICE,AMT_ANNUITY,REGION_POPULATION_RELATIVE,DAYS_ID_PUBLISH
0,0.139376,0.262949,0.083037,351000.0,24700.5,0.018801,-2120
1,NaN,0.622246,0.311267,1129500.0,35698.5,0.003541,-291
2,0.729567,0.555912,NaN,135000.0,6750.0,0.010032,-2531
3,NaN,0.650442,NaN,297000.0,29686.5,0.008019,-2437
4,NaN,0.322738,NaN,513000.0,21865.5,0.028663,-3458

In [541]:
cluster_train.head()

,EXT_SOURCE_3,EXT_SOURCE_2,EXT_SOURCE_1,AMT_GOODS_PRICE,AMT_ANNUITY,REGION_POPULATION_RELATIVE,DAYS_ID_PUBLISH,TARGET
0,-2.153651,-1.317940,-3.021877,-0.507236,-0.166143,-0.149452,0.579154,1
1,0.112063,0.564482,-1.384737,1.600873,0.592683,-1.252750,1.790855,0
2,1.223975,0.216948,0.012103,-1.092145,-1.404669,-0.783451,0.306869,0
3,0.112063,0.712205,0.012103,-0.653463,0.177874,-0.928991,0.369143,0
4,0.112063,-1.004691,0.012103,-0.068554,-0.361749,0.563570,-0.307263,0

In [535]:
t=cluster_train
t['TARGET']=application_train['TARGET']
class_0=t[t['TARGET']==0]
class_0=class_0.drop('TARGET',axis=1)
class_1=t[t['TARGET']==1]
class_1=class_1.drop('TARGET',axis=1)
kmeans_0 = KMeans(n_clusters=1).fit(class_0)
kmeans_1 = KMeans(n_clusters=1).fit(class_1)

In [543]:
cluster_train=cluster_train.drop('TARGET',axis=1)
cluster_train.head()

ValueError: labels ['TARGET'] not contained in axis

In [553]:
cluster_new.head()

,EXT_SOURCE_3,EXT_SOURCE_2,EXT_SOURCE_1,AMT_GOODS_PRICE,AMT_ANNUITY,REGION_POPULATION_RELATIVE,DAYS_ID_PUBLISH
0,-2.038369,1.441565,1.781131,-0.239153,-0.451790,-0.145910,1.445696
1,-0.473477,-1.167540,0.435266,-0.970289,-0.671924,1.078997,0.908413
2,0.545375,0.970733,0.012103,0.248271,2.943988,-0.127762,-0.337075
3,0.555178,-0.025286,0.153673,2.807247,1.511720,0.399377,-0.804133
4,0.112063,-0.465323,-2.167493,0.236086,0.342121,-0.783451,-0.839908

In [556]:
cluster_new_feats.head()

,cluster_0_dist,cluster_1_dist,cluster_2_dist,cluster_3_dist,cluster_4_dist,cluster_5_dist,sum_dist,diff_0,diff_1,diff_2,diff_3,diff_4,diff_5,diff_6,diff_7,diff_8,diff_9,diff_10,diff_11,diff_12,diff_13,diff_14,diff_15,diff_16,diff_17,diff_18,diff_19,diff_20
0,4.291996,4.517610,3.007957,3.833934,4.203408,3.211097,23.066002,-0.225614,1.284039,0.458063,0.088588,1.080900,-18.774006,1.509653,0.683677,0.314202,1.306514,-18.548392,-0.825976,-1.195451,-0.203139,-20.058045,-0.369475,0.622837,-19.232069,0.992312,-18.862594,-19.854906
1,3.344024,2.077542,2.465493,2.871533,3.957417,2.259129,16.975137,1.266482,0.878531,0.472491,-0.613393,1.084895,-13.631113,-0.387951,-0.793990,-1.879875,-0.181587,-14.897595,-0.406039,-1.491924,0.206365,-14.509644,-1.085884,0.612404,-14.103604,1.698288,-13.017720,-14.716008
2,3.740385,4.264246,4.053761,3.524220,2.175727,3.728081,21.486420,-0.523861,-0.313375,0.216165,1.564658,0.012304,-17.746035,0.210485,0.740026,2.088519,0.536165,-17.222174,0.529540,1.878034,0.325680,-17.432659,1.348493,-0.203860,-17.962200,-1.552354,-19.310693,-17.758339
3,3.651099,4.176760,4.322104,3.848098,1.620986,4.229741,21.848787,-0.525662,-0.671005,-0.196999,2.030112,-0.578642,-18.197689,-0.145344,0.328662,2.555774,-0.052981,-17.672027,0.474006,2.701118,0.092363,-17.526683,2.227112,-0.381643,-18.000689,-2.608755,-20.227801,-17.619047
4,4.572483,2.576434,2.857448,2.876549,3.206871,3.154442,19.244228,1.996048,1.715035,1.695934,1.365612,1.418041,-14.671745,-0.281014,-0.300114,-0.630437,-0.578008,-16.667793,-0.019101,-0.349423,-0.296994,-16.386779,-0.330322,-0.277893,-16.367679,0.052429,-16.037357,-16.089786

In [564]:
# Manually finding the cluster centroid using k-means and creating distance based features

t=cluster_train
t['TARGET']=application_train['TARGET']
class_0=t[t['TARGET']==0]
class_0=class_0.drop('TARGET',axis=1)
class_1=t[t['TARGET']==1]
class_1=class_1.drop('TARGET',axis=1)
kmeans_0 = KMeans(n_clusters=1).fit(class_0)
kmeans_1 = KMeans(n_clusters=1).fit(class_1)

distances1 = np.column_stack([np.sum((cluster_train.values - center)**2, axis=1)**0.5 for center in kmeans_0.cluster_centers_])
train_feats1=pd.DataFrame(distances1)

distances2 = np.column_stack([np.sum((cluster_train.values - center)**2, axis=1)**0.5 for center in kmeans_1.cluster_centers_])
train_feats1['dist2']=pd.DataFrame(distances2)[0]

train_feats1.columns=['dist1','dist2']
train_feats1['dist_diff']=train_feats1['dist1']-train_feats1['dist2']

distances1 = np.column_stack([np.sum((cluster_new.values - center)**2, axis=1)**0.5 for center in kmeans_0.cluster_centers_])
new_feats1=pd.DataFrame(distances1)

distances2 = np.column_stack([np.sum((cluster_new.values - center)**2, axis=1)**0.5 for center in kmeans_1.cluster_centers_])
new_feats1['dist2']=pd.DataFrame(distances2)[0]

new_feats1.columns=['dist1','dist2']
new_feats1['dist_diff']=new_feats1['dist1']-new_feats1['dist2']

train_feats1=pd.merge(train_feats1,cluster_train_feats,left_index=True,right_index=True)

new_feats1=pd.merge(new_feats1,cluster_new_feats,left_index=True,right_index=True)

RangeIndex(start=0, stop=307511, step=1)

In [567]:
train_feats1.head()

,dist1,dist2,dist_diff,cluster_0_dist,cluster_1_dist,cluster_2_dist,cluster_3_dist,cluster_4_dist,cluster_5_dist,sum_dist,diff_0,diff_1,diff_2,diff_3,diff_4,diff_5,diff_6,diff_7,diff_8,diff_9,diff_10,diff_11,diff_12,diff_13,diff_14,diff_15,diff_16,diff_17,diff_18,diff_19,diff_20
0,4.085433,3.286156,0.799277,5.502717,3.666701,2.995869,4.763041,5.105046,4.148163,26.181537,1.836016,2.506848,0.739676,0.397671,1.354554,-20.678820,0.670832,-1.096340,-1.438345,-0.481462,-22.514836,-1.767172,-2.109177,-1.152294,-23.185668,-0.342005,0.614878,-21.418496,0.956883,-21.076491,-22.033374
1,3.162657,3.167453,-0.004796,4.809484,3.895591,3.547261,3.975053,2.873999,2.825102,21.926490,0.913893,1.262223,0.834431,1.935485,1.984383,-17.117006,0.348330,-0.079462,1.021592,1.070489,-18.030899,-0.427792,0.673262,0.722160,-18.379229,1.101054,1.149952,-17.951437,0.048897,-19.052491,-19.101388
2,2.313758,2.641798,-0.328040,4.558543,2.565574,3.298268,1.899861,4.056379,1.931120,18.309746,1.992969,1.260275,2.658682,0.502164,2.627423,-13.751203,-0.732694,0.665713,-1.490805,0.634454,-15.744172,1.398407,-0.758111,1.367148,-15.011478,-2.156519,-0.031260,-16.409885,2.125259,-14.253367,-16.378625
3,1.396662,1.760605,-0.363943,3.859782,2.522653,2.185543,1.624115,2.721383,1.321756,14.235231,1.337129,1.674239,2.235667,1.138399,2.538025,-10.375449,0.337110,0.898538,-0.198730,1.200896,-11.712578,0.561428,-0.535840,0.863787,-12.049688,-1.097268,0.302359,-12.611116,1.399627,-11.513848,-12.913475
4,1.281557,1.246517,0.035040,3.047335,1.141510,2.195033,1.780992,2.820323,2.121831,13.107025,1.905825,0.852302,1.266343,0.227012,0.925504,-10.059690,-1.053524,-0.639483,-1.678813,-0.980322,-11.965516,0.414041,-0.625290,0.073202,-10.911992,-1.039331,-0.340839,-11.326033,0.698492,-10.286702,-10.985194

In [508]:
col_names=['cluster_'+str(i)+'_dist' for i in range(6)]
cluster_train_feats=pd.DataFrame(kmeans.transform(cluster_train))
cluster_train_feats.columns=col_names
cluster_new_feats=pd.DataFrame(kmeans.transform(cluster_new))
cluster_new_feats.columns=col_names

cluster_train_feats['sum_dist']=cluster_train_feats.sum(axis=1)
cluster_new_feats['sum_dist']=cluster_new_feats.sum(axis=1)

In [563]:
cluster_new_feats.index

RangeIndex(start=0, stop=48744, step=1)

In [510]:
cluster_train_feats.head()

,cluster_0_dist,cluster_1_dist,cluster_2_dist,cluster_3_dist,cluster_4_dist,cluster_5_dist,sum_dist
0,5.502717,3.666701,2.995869,4.763041,5.105046,4.148163,26.181537
1,4.809484,3.895591,3.547261,3.975053,2.873999,2.825102,21.926490
2,4.558543,2.565574,3.298268,1.899861,4.056379,1.931120,18.309746
3,3.859782,2.522653,2.185543,1.624115,2.721383,1.321756,14.235231
4,3.047335,1.141510,2.195033,1.780992,2.820323,2.121831,13.107025

In [511]:
from itertools import combinations
comb_list=list(combinations(cluster_train_feats.columns, 2))
diff_cols=['diff_'+str(i) for i in range(len(comb_list))]
i=0
for comb in comb_list:
    cluster_train_feats[diff_cols[i]]=cluster_train_feats[comb[0]]-cluster_train_feats[comb[1]]
    cluster_new_feats[diff_cols[i]]=cluster_new_feats[comb[0]]-cluster_new_feats[comb[1]]
    i=i+1

In [513]:
cluster_train_feats.shape

(307511, 28)

In [499]:
cluster_new_feats.head()

,cluster_0_dist,cluster_1_dist,cluster_2_dist,cluster_3_dist,cluster_4_dist,cluster_5_dist,diff_0,diff_1,diff_2,diff_3,diff_4,diff_5,diff_6,diff_7,diff_8,diff_9,diff_10,diff_11,diff_12,diff_13,diff_14
0,4.291996,4.517610,3.007957,3.833934,4.203408,3.211097,-0.225614,1.284039,0.458063,0.088588,1.080900,1.509653,0.683677,0.314202,1.306514,-0.825976,-1.195451,-0.203139,-0.369475,0.622837,0.992312
1,3.344024,2.077542,2.465493,2.871533,3.957417,2.259129,1.266482,0.878531,0.472491,-0.613393,1.084895,-0.387951,-0.793990,-1.879875,-0.181587,-0.406039,-1.491924,0.206365,-1.085884,0.612404,1.698288
2,3.740385,4.264246,4.053761,3.524220,2.175727,3.728081,-0.523861,-0.313375,0.216165,1.564658,0.012304,0.210485,0.740026,2.088519,0.536165,0.529540,1.878034,0.325680,1.348493,-0.203860,-1.552354
3,3.651099,4.176760,4.322104,3.848098,1.620986,4.229741,-0.525662,-0.671005,-0.196999,2.030112,-0.578642,-0.145344,0.328662,2.555774,-0.052981,0.474006,2.701118,0.092363,2.227112,-0.381643,-2.608755
4,4.572483,2.576434,2.857448,2.876549,3.206871,3.154442,1.996048,1.715035,1.695934,1.365612,1.418041,-0.281014,-0.300114,-0.630437,-0.578008,-0.019101,-0.349423,-0.296994,-0.330322,-0.277893,0.052429

In [514]:
cluster_train_feats.head()

,cluster_0_dist,cluster_1_dist,cluster_2_dist,cluster_3_dist,cluster_4_dist,cluster_5_dist,sum_dist,diff_0,diff_1,diff_2,diff_3,diff_4,diff_5,diff_6,diff_7,diff_8,diff_9,diff_10,diff_11,diff_12,diff_13,diff_14,diff_15,diff_16,diff_17,diff_18,diff_19,diff_20
0,5.502717,3.666701,2.995869,4.763041,5.105046,4.148163,26.181537,1.836016,2.506848,0.739676,0.397671,1.354554,-20.678820,0.670832,-1.096340,-1.438345,-0.481462,-22.514836,-1.767172,-2.109177,-1.152294,-23.185668,-0.342005,0.614878,-21.418496,0.956883,-21.076491,-22.033374
1,4.809484,3.895591,3.547261,3.975053,2.873999,2.825102,21.926490,0.913893,1.262223,0.834431,1.935485,1.984383,-17.117006,0.348330,-0.079462,1.021592,1.070489,-18.030899,-0.427792,0.673262,0.722160,-18.379229,1.101054,1.149952,-17.951437,0.048897,-19.052491,-19.101388
2,4.558543,2.565574,3.298268,1.899861,4.056379,1.931120,18.309746,1.992969,1.260275,2.658682,0.502164,2.627423,-13.751203,-0.732694,0.665713,-1.490805,0.634454,-15.744172,1.398407,-0.758111,1.367148,-15.011478,-2.156519,-0.031260,-16.409885,2.125259,-14.253367,-16.378625
3,3.859782,2.522653,2.185543,1.624115,2.721383,1.321756,14.235231,1.337129,1.674239,2.235667,1.138399,2.538025,-10.375449,0.337110,0.898538,-0.198730,1.200896,-11.712578,0.561428,-0.535840,0.863787,-12.049688,-1.097268,0.302359,-12.611116,1.399627,-11.513848,-12.913475
4,3.047335,1.141510,2.195033,1.780992,2.820323,2.121831,13.107025,1.905825,0.852302,1.266343,0.227012,0.925504,-10.059690,-1.053524,-0.639483,-1.678813,-0.980322,-11.965516,0.414041,-0.625290,0.073202,-10.911992,-1.039331,-0.340839,-11.326033,0.698492,-10.286702,-10.985194

In [448]:
c=pd.merge(a,b,left_index=True,right_index=True)
svm = SVC().fit(c.values, y)
svm.score(c.values, y)

0.98

In [408]:
tmp_removal=['EMERGENCYSTATE_MODE',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'NAME_TYPE_SUITE',
 'OCCUPATION_TYPE',
 'WALLSMATERIAL_MODE']

cat_miss_pipes = []
for col in tmp_removal:
    cat_miss_pipes.append(('miss_impute_'+col, CustomCategoryImputer(col=col)))

one_hot_columns1=['EMERGENCYSTATE_MODE','FONDKAPREMONT_MODE','HOUSETYPE_MODE','NAME_EDUCATION_TYPE','NAME_FAMILY_STATUS',
                 'NAME_HOUSING_TYPE','NAME_INCOME_TYPE','WALLSMATERIAL_MODE','WEEKDAY_APPR_PROCESS_START']

one_hot_columns1=['EMERGENCYSTATE_MODE']

all_pipes = []

one_hot_pipes = []
for col in one_hot_columns1:
    one_hot_pipes.append(('one_hot_' + col, CreateOneHotEncoding(categorical_column=col)))

all_pipes.append(Pipeline(cat_miss_pipes))
all_pipes.append(Pipeline(one_hot_pipes))
all_pipelines = []
count = 1
for pipe in all_pipes:
    all_pipelines.append(('feature_set' + str(count), pipe))
    count += 1
final_pipeline=Pipeline(all_pipelines)
final_pipeline.fit(application_train)
new_dat_train=final_pipeline.transform(application_train)
new_dat_new=final_pipeline.transform(application_newData)

cols=list(set(new_dat_train.columns)-set(application_train.columns))
new_dat_train=new_dat_train[cols]
new_dat_new=new_dat_new[cols]

In [413]:
cols

['emergencystate_mode_no', 'emergencystate_mode_yes']

In [403]:
feat_weights

                                    feat_name         0
0    EXT_SOURCE_3                              0.342958
1    EXT_SOURCE_2                              0.255334
2    EXT_SOURCE_1                              0.114284
3    EXT_SOURCE_1_is_missing                   0.075403
4    AMT_GOODS_PRICE                           0.073957
5    AMT_ANNUITY                               0.069739
6    REGION_POPULATION_RELATIVE                0.063206
7    DAYS_ID_PUBLISH                           0.061460
8    NAME_EDUCATION_TYPE_freq                  0.059415
9    occupation_type_secretaries               0.058782
10   OWN_CAR_AGE                               0.058301
11   DEF_60_CNT_SOCIAL_CIRCLE                  0.057516
12   occupation_type_medicine_staff            0.054533
13   REG_CITY_NOT_LIVE_CITY                    0.054274
14   NAME_INCOME_TYPE_freq                     0.050247
15   AMT_REQ_CREDIT_BUREAU_DAY                 0.050193
16   AMT_REQ_CREDIT_BUREAU_QRT                 0.048834
17   organization_type_industry:_type_12       0.048580
18   TOTALAREA_MODE                            0.048464
19   organization_type_bank                    0.047909
20   organization_type_medicine                0.047420
21   occupation_type_security_staff            0.047215
22   occupation_type_sales_staff               0.046844
23   FLAG_DOCUMENT_9_freq                      0.045541
24   FLAG_DOCUMENT_9                           0.045541
25   organization_type_trade:_type_6           0.045521
26   AMT_REQ_CREDIT_BUREAU_MON                 0.045423
27   DEF_30_CNT_SOCIAL_CIRCLE                  0.044119
28   HOUR_APPR_PROCESS_START                   0.043575
29   occupation_type_low-skill_laborers        0.040720
30   AMT_REQ_CREDIT_BUREAU_WEEK                0.040497
31   FLAG_WORK_PHONE_freq                      0.040041
32   FLAG_WORK_PHONE                           0.040041
33   DAYS_REGISTRATION                         0.038710
34   REGION_RATING_CLIENT_freq                 0.038593
35   FLAG_DOCUMENT_14                          0.038411
36   FLAG_DOCUMENT_14_freq                     0.038411
37   occupation_type_accountants               0.038201
38   organization_type_industry:_type_4        0.037830
39   organization_type_industry:_type_1        0.037542
40   FLAG_DOCUMENT_3                           0.035044
41   FLAG_DOCUMENT_3_freq                      0.035044
42   AMT_GOODS_PRICE_is_missing                0.034926
43   FLAG_DOCUMENT_16                          0.034356
44   FLAG_DOCUMENT_16_freq                     0.034356
45   code_gender_f                             0.034352
46   CODE_GENDER_freq                          0.034352
47   code_gender_m                             0.034352
48   ELEVATORS_AVG                             0.034154
49   organization_type_telecom                 0.032930
50   organization_type_industry:_type_2        0.032306
51   ORGANIZATION_TYPE_freq                    0.032235
52   FLAG_PHONE                                0.031663
53   FLAG_PHONE_freq                           0.031663
54   FLAG_CONT_MOBILE_freq                     0.030867
55   FLAG_CONT_MOBILE                          0.030867
56   LIVINGAPARTMENTS_MODE                     0.030688
57   YEARS_BEGINEXPLUATATION_MEDI              0.029857
58   LANDAREA_AVG                              0.029735
59   occupation_type_core_staff                0.029224
60   organization_type_trade:_type_1           0.028715
61   LIVINGAPARTMENTS_MEDI                     0.028143
62   organization_type_industry:_type_13       0.027897
63   organization_type_legal_services          0.027819
64   ELEVATORS_MEDI                            0.027272
65   ELEVATORS_MODE_is_missing                 0.027221
66   ELEVATORS_MEDI_is_missing                 0.027221
67   ELEVATORS_AVG_is_missing                  0.027221
68   name_contract_type_revolving_loans        0.027136
69   name_contract_type_cash_loans             0.027136
70   NAME_CONTRACT_TYPE_freq                   0.027136
71   FLOORSMIN_MODE                            0.026440
72   FLAG_DOCUMENT_15_freq                     0.026183
73   FLAG_DOCUMENT_15                          0.026183
74   occupation_type_managers                  0.026161
75   organization_type_trade:_type_3           0.025942
76   organization_type_restaurant              0.025848
77   CNT_CHILDREN                              0.025629
78   organization_type_realtor                 0.025438
79   organization_type_kindergarten            0.025351
80   NAME_FAMILY_STATUS_freq                   0.024998
81   LIVINGAREA_AVG                            0.024921
82   LANDAREA_MEDI                             0.024180
83   OBS_60_CNT_SOCIAL_CIRCLE                  0.023856
84   organization_type_self-employed           0.023482
85   LANDAREA_MODE                             0.023178
86   OBS_30_CNT_SOCIAL_CIRCLE                  0.022671
87   BASEMENTAREA_MODE                         0.022446
88   organization_type_government              0.022441
89   organization_type_hotel                   0.022367
90   NONLIVINGAREA_MODE                        0.022117
91   organization_type_industry:_type_6        0.021458
92   NAME_HOUSING_TYPE_freq                    0.021411
93   YEARS_BEGINEXPLUATATION_AVG               0.021360
94   organization_type_transport:_type_4       0.021213
95   occupation_type_cooking_staff             0.020995
96   organization_type_business_entity_type_3  0.020841
97   organization_type_transport:_type_1       0.020784
98   COMMONAREA_AVG_is_missing                 0.020714
99   COMMONAREA_MEDI_is_missing                0.020714
100  COMMONAREA_MODE_is_missing                0.020714
101  FLAG_DOCUMENT_17                          0.020431
102  FLAG_DOCUMENT_17_freq                     0.020431
103  organization_type_industry:_type_11       0.020390
104  organization_type_industry:_type_9        0.020058
105  organization_type_housing                 0.019948
106  ENTRANCES_MODE                            0.019798
107  organization_type_industry:_type_3        0.019759
108  AMT_INCOME_TOTAL                          0.019546
109  YEARS_BEGINEXPLUATATION_MODE              0.019506
110  DAYS_LAST_PHONE_CHANGE                    0.019349
111  organization_type_religion                0.018733
112  LIVINGAPARTMENTS_MODE_is_missing          0.018733
113  LIVINGAPARTMENTS_MEDI_is_missing          0.018733
114  LIVINGAPARTMENTS_AVG_is_missing           0.018733
115  APARTMENTS_MODE                           0.018693
116  occupation_type_high_skill_tech_staff     0.018563
117  FLOORSMAX_AVG                             0.018492
118  FLAG_DOCUMENT_21_freq                     0.017949
119  FLAG_DOCUMENT_21                          0.017949
120  organization_type_trade:_type_4           0.017477
121  DAYS_BIRTH                                0.016928
122  FLAG_DOCUMENT_5                           0.016921
123  FLAG_DOCUMENT_5_freq                      0.016921
124  BASEMENTAREA_AVG_is_missing               0.016796
125  BASEMENTAREA_MODE_is_missing              0.016796
126  BASEMENTAREA_MEDI_is_missing              0.016796
127  WEEKDAY_APPR_PROCESS_START_freq           0.016763
128  organization_type_transport:_type_3       0.016589
129  occupation_type_it_staff                  0.016514
130  organization_type_military                0.016473
131  flag_own_car_n                            0.016268
132  OWN_CAR_AGE_is_missing                    0.016268
133  flag_own_car_y                            0.016268
134  FLAG_OWN_CAR_freq                         0.016268
135  occupation_type_realty_agents             0.016134
136  LIVINGAREA_MEDI                           0.015470
137  organization_type_trade:_type_7           0.014962
138  EXT_SOURCE_3_is_missing                   0.014794
139  COMMONAREA_AVG                            0.014726
140  organization_type_industry:_type_10       0.014715
141  LIVINGAPARTMENTS_AVG                      0.014553
142  REGION_RATING_CLIENT_W_CITY_freq          0.014330
143  TOTALAREA_MODE_is_missing                 0.014319
144  FLAG_EMAIL_freq                           0.014237
145  FLAG_EMAIL                                0.014237
146  FLAG_DOCUMENT_19_freq                     0.014036
147  FLAG_DOCUMENT_19                          0.014036
148  organization_type_business_entity_type_1  0.013527
149  FLOORSMAX_MEDI                            0.013408
150  YEARS_BUILD_MEDI                          0.013371
151  COMMONAREA_MEDI                           0.013220
152  DAYS_EMPLOYED                             0.013145
153  FLOORSMIN_MEDI                            0.013085
154  YEARS_BUILD_AVG                           0.013055
155  organization_type_security_ministries     0.012884
156  AMT_REQ_CREDIT_BUREAU_HOUR                0.012540
157  organization_type_police                  0.012534
158  organization_type_electricity             0.012527
159  organization_type_other                   0.012509
160  ELEVATORS_MODE                            0.012438
161  FLOORSMIN_AVG                             0.012405
162  organization_type_emergency               0.012314
163  FLAG_DOCUMENT_7                           0.012296
164  FLAG_DOCUMENT_7_freq                      0.012296
165  AMT_REQ_CREDIT_BUREAU_YEAR                0.012086
166  AMT_REQ_CREDIT_BUREAU_YEAR_is_missing     0.011933
167  AMT_REQ_CREDIT_BUREAU_HOUR_is_missing     0.011933
168  AMT_REQ_CREDIT_BUREAU_QRT_is_missing      0.011933
169  AMT_REQ_CREDIT_BUREAU_MON_is_missing      0.011933
170  AMT_REQ_CREDIT_BUREAU_DAY_is_missing      0.011933
171  AMT_REQ_CREDIT_BUREAU_WEEK_is_missing     0.011933
172  LIVE_REGION_NOT_WORK_REGION               0.011873
173  LIVE_REGION_NOT_WORK_REGION_freq          0.011873
174  REG_CITY_NOT_WORK_CITY_freq               0.011753
175  REG_CITY_NOT_WORK_CITY                    0.011753
176  organization_type_trade:_type_5           0.011741
177  ENTRANCES_MEDI                            0.011602
178  occupation_type_laborers                  0.011450
179  FLAG_DOCUMENT_11_freq                     0.011410
180  FLAG_DOCUMENT_11                          0.011410
181  organization_type_trade:_type_2           0.010913
182  organization_type_security                0.010876
183  organization_type_university              0.010395
184  organization_type_culture                 0.010247
185  organization_type_advertising             0.009951
186  REG_REGION_NOT_LIVE_REGION                0.009819
187  REG_REGION_NOT_LIVE_REGION_freq           0.009819
188  ENTRANCES_MODE_is_missing                 0.009746
189  ENTRANCES_MEDI_is_missing                 0.009746
190  ENTRANCES_AVG_is_missing                  0.009746
191  LIVINGAREA_MODE_is_missing                0.009640
192  LIVINGAREA_AVG_is_missing                 0.009640
193  LIVINGAREA_MEDI_is_missing                0.009640
194  organization_type_services                0.009570
195  BASEMENTAREA_MEDI                         0.009327
196  organization_type_postal                  0.008959
197  NONLIVINGAPARTMENTS_MODE                  0.008848
198  FLAG_DOCUMENT_20_freq                     0.008819
199  FLAG_DOCUMENT_20                          0.008819
200  CNT_CHILDREN_freq                         0.008398
201  occupation_type_hr_staff                  0.008372
202  occupation_type_cleaning_staff            0.008370
203  ENTRANCES_AVG                             0.008173
204  organization_type_xna                     0.007901
205  FLAG_EMP_PHONE_freq                       0.007901
206  FLAG_EMP_PHONE                            0.007901
207  NONLIVINGAREA_AVG                         0.007723
208  organization_type_business_entity_type_2  0.007658
209  NONLIVINGAPARTMENTS_MEDI_is_missing       0.007568
210  NONLIVINGAPARTMENTS_MODE_is_missing       0.007568
211  NONLIVINGAPARTMENTS_AVG_is_missing        0.007568
212  APARTMENTS_MEDI                           0.007340
213  NONLIVINGAREA_MEDI                        0.007194
214  FLAG_DOCUMENT_4_freq                      0.006719
215  FLAG_DOCUMENT_4                           0.006719
216  FLOORSMIN_AVG_is_missing                  0.006563
217  FLOORSMIN_MODE_is_missing                 0.006563
218  FLOORSMIN_MEDI_is_missing                 0.006563
219  organization_type_mobile                  0.006411
220  APARTMENTS_AVG                            0.006304
221  organization_type_industry:_type_5        0.006294
222  FLAG_DOCUMENT_8                           0.006132
223  FLAG_DOCUMENT_8_freq                      0.006132
224  NONLIVINGAREA_MODE_is_missing             0.006116
225  NONLIVINGAREA_AVG_is_missing              0.006116
226  NONLIVINGAREA_MEDI_is_missing             0.006116
227  FLOORSMAX_MODE                            0.006052
228  LIVINGAREA_MODE                           0.006039
229  LIVE_CITY_NOT_WORK_CITY_freq              0.005797
230  LIVE_CITY_NOT_WORK_CITY                   0.005797
231  FLAG_DOCUMENT_18                          0.005754
232  FLAG_DOCUMENT_18_freq                     0.005754
233  EXT_SOURCE_2_is_missing                   0.005438
234  occupation_type_drivers                   0.005377
235  organization_type_agriculture             0.005322
236  COMMONAREA_MODE                           0.005010
237  NONLIVINGAPARTMENTS_MEDI                  0.004989
238  occupation_type_waiters/barmen_staff      0.004933
239  organization_type_construction            0.004416
240  NONLIVINGAPARTMENTS_AVG                   0.004322
241  flag_own_realty_n                         0.004034
242  flag_own_realty_y                         0.004034
243  FLAG_OWN_REALTY_freq                      0.004034
244  REG_REGION_NOT_WORK_REGION_freq           0.003820
245  REG_REGION_NOT_WORK_REGION                0.003820
246  YEARS_BEGINEXPLUATATION_AVG_is_missing    0.003386
247  YEARS_BEGINEXPLUATATION_MEDI_is_missing   0.003386
248  YEARS_BEGINEXPLUATATION_MODE_is_missing   0.003386
249  organization_type_cleaning                0.003352
250  LANDAREA_AVG_is_missing                   0.002735
251  LANDAREA_MODE_is_missing                  0.002735
252  LANDAREA_MEDI_is_missing                  0.002735
253  OBS_30_CNT_SOCIAL_CIRCLE_is_missing       0.002603
254  DEF_30_CNT_SOCIAL_CIRCLE_is_missing       0.002603
255  DEF_60_CNT_SOCIAL_CIRCLE_is_missing       0.002603
256  OBS_60_CNT_SOCIAL_CIRCLE_is_missing       0.002603
257  occupation_type_private_service_staff     0.002415
258  organization_type_insurance               0.002321
259  FLAG_DOCUMENT_6                           0.002310
260  FLAG_DOCUMENT_6_freq                      0.002310
261  YEARS_BUILD_MEDI_is_missing               0.002098
262  YEARS_BUILD_AVG_is_missing                0.002098
263  YEARS_BUILD_MODE_is_missing               0.002098
264  organization_type_transport:_type_2       0.001774
265  APARTMENTS_AVG_is_missing                 0.001481
266  APARTMENTS_MEDI_is_missing                0.001481
267  APARTMENTS_MODE_is_missing                0.001481
268  CNT_FAM_MEMBERS                           0.001148
269  organization_type_school                  0.000882
270  AMT_CREDIT                                0.000864
271  YEARS_BUILD_MODE                          0.000430
272  organization_type_industry:_type_7        0.000372
273  FLAG_DOCUMENT_13_freq                     0.000314
274  FLAG_DOCUMENT_13                          0.000314
275  FLOORSMAX_MEDI_is_missing                 0.000193
276  FLOORSMAX_MODE_is_missing                 0.000193
277  FLOORSMAX_AVG_is_missing                  0.000193
278  BASEMENTAREA_AVG                          0.000177
279  REG_CITY_NOT_WORK_CITY_is_missing         0.000000
280  REGION_POPULATION_RELATIVE_is_missing     0.000000
281  FLAG_DOCUMENT_11_is_missing               0.000000
282  FLAG_DOCUMENT_9_is_missing                0.000000
283  FLAG_DOCUMENT_3_is_missing                0.000000
284  FLAG_DOCUMENT_10_freq                     0.000000
285  DAYS_ID_PUBLISH_is_missing                0.000000
286  FLAG_DOCUMENT_7_is_missing                0.000000
287  REG_CITY_NOT_LIVE_CITY_is_missing         0.000000
288  FLAG_DOCUMENT_13_is_missing               0.000000
289  FLAG_WORK_PHONE_is_missing                0.000000
290  CNT_FAM_MEMBERS_is_missing                0.000000
291  AMT_ANNUITY_is_missing                    0.000000
292  CNT_CHILDREN_is_missing                   0.000000
293  REG_REGION_NOT_LIVE_REGION_is_missing     0.000000
294  FLAG_PHONE_is_missing                     0.000000
295  FLAG_EMAIL_is_missing                     0.000000
296  FLAG_DOCUMENT_14_is_missing               0.000000
297  FLAG_DOCUMENT_19_is_missing               0.000000
298  FLAG_DOCUMENT_15_is_missing               0.000000
299  FLAG_DOCUMENT_17_is_missing               0.000000
300  FLAG_DOCUMENT_12_freq                     0.000000
301  FLAG_DOCUMENT_2_freq                      0.000000
302  FLAG_MOBIL_freq                           0.000000
303  FLAG_DOCUMENT_20_is_missing               0.000000
304  DAYS_LAST_PHONE_CHANGE_is_missing         0.000000
305  AMT_INCOME_TOTAL_is_missing               0.000000
306  AMT_CREDIT_is_missing                     0.000000
307  DAYS_REGISTRATION_is_missing              0.000000
308  FLAG_DOCUMENT_4_is_missing                0.000000
309  FLAG_DOCUMENT_5_is_missing                0.000000
310  DAYS_BIRTH_is_missing                     0.000000
311  FLAG_DOCUMENT_6_is_missing                0.000000
312  FLAG_CONT_MOBILE_is_missing               0.000000
313  LIVE_REGION_NOT_WORK_REGION_is_missing    0.000000
314  REG_REGION_NOT_WORK_REGION_is_missing     0.000000
315  LIVE_CITY_NOT_WORK_CITY_is_missing        0.000000
316  FLAG_DOCUMENT_21_is_missing               0.000000
317  FLAG_DOCUMENT_18_is_missing               0.000000
318  FLAG_EMP_PHONE_is_missing                 0.000000
319  FLAG_DOCUMENT_16_is_missing               0.000000
320  DAYS_EMPLOYED_is_missing                  0.000000
321  FLAG_DOCUMENT_8_is_missing                0.000000
322  HOUR_APPR_PROCESS_START_is_missing        0.000000

In [65]:
summ=DataSummary.returnSummaryDataFrame(application_train)
summT=summ.transpose()
summT=summT[list(set(summT.columns)-set(['unique_values']))]

In [83]:
desc=home_credit_col_desc[['Row','Description']]
desc.columns=['feat_name','desc']

In [89]:
pd.DataFrame(tmp[['feat_name']].feat_name.str.split('_',1).tolist(),
                                   columns = ['flips','row'])

                  flips                     row
0   APARTMENTS           AVG
1   APARTMENTS           MEDI
2   APARTMENTS           MODE
3   BASEMENTAREA         AVG
4   BASEMENTAREA         MEDI
5   BASEMENTAREA         MODE
6   COMMONAREA           AVG
7   COMMONAREA           MEDI
8   COMMONAREA           MODE
9   ELEVATORS            AVG
10  ELEVATORS            MEDI
11  ELEVATORS            MODE
12  ENTRANCES            AVG
13  ENTRANCES            MEDI
14  ENTRANCES            MODE
15  FLAG                 CONT_MOBILE
16  FLAG                 DOCUMENT_10
17  FLAG                 DOCUMENT_11
18  FLAG                 DOCUMENT_12
19  FLAG                 DOCUMENT_13
20  FLAG                 DOCUMENT_14
21  FLAG                 DOCUMENT_15
22  FLAG                 DOCUMENT_16
23  FLAG                 DOCUMENT_17
24  FLAG                 DOCUMENT_18
25  FLAG                 DOCUMENT_19
26  FLAG                 DOCUMENT_2
27  FLAG                 DOCUMENT_20
28  FLAG                 DOCUMENT_21
29  FLAG                 DOCUMENT_3
30  FLAG                 DOCUMENT_4
31  FLAG                 DOCUMENT_5
32  FLAG                 DOCUMENT_6
33  FLAG                 DOCUMENT_7
34  FLAG                 DOCUMENT_8
35  FLAG                 DOCUMENT_9
36  FLAG                 EMAIL
37  FLAG                 EMP_PHONE
38  FLAG                 MOBIL
39  FLAG                 PHONE
40  FLAG                 WORK_PHONE
41  FLOORSMAX            AVG
42  FLOORSMAX            MEDI
43  FLOORSMAX            MODE
44  FLOORSMIN            AVG
45  FLOORSMIN            MEDI
46  FLOORSMIN            MODE
47  LANDAREA             AVG
48  LANDAREA             MEDI
49  LANDAREA             MODE
50  LIVE                 CITY_NOT_WORK_CITY
51  LIVE                 REGION_NOT_WORK_REGION
52  LIVINGAPARTMENTS     AVG
53  LIVINGAPARTMENTS     MEDI
54  LIVINGAPARTMENTS     MODE
55  LIVINGAREA           AVG
56  LIVINGAREA           MEDI
57  LIVINGAREA           MODE
58  NONLIVINGAPARTMENTS  AVG
59  NONLIVINGAPARTMENTS  MEDI
60  NONLIVINGAPARTMENTS  MODE
61  NONLIVINGAREA        AVG
62  NONLIVINGAREA        MEDI
63  NONLIVINGAREA        MODE
64  REG                  CITY_NOT_LIVE_CITY
65  REG                  CITY_NOT_WORK_CITY
66  REG                  REGION_NOT_LIVE_REGION
67  REG                  REGION_NOT_WORK_REGION
68  TARGET               None
69  TOTALAREA            MODE
70  YEARS                BEGINEXPLUATATION_AVG
71  YEARS                BEGINEXPLUATATION_MEDI
72  YEARS                BEGINEXPLUATATION_MODE
73  YEARS                BUILD_AVG
74  YEARS                BUILD_MEDI
75  YEARS                BUILD_MODE

In [124]:
feat_weights=pd.read_csv("C:/Users/vberlia/Documents/feat_weights.csv")
tmp=summT[(summT['min']==0) & (summT['max']==1)]
tmp.insert(0,'feat_name',tmp.index)
tmp=pd.merge(tmp,feat_weights,on='feat_name',how='left')
# tmp=pd.merge(tmp,desc,on='feat_name',how='left')
tmp

,feat_name,std,75%,count_unique,count,mode,col_type,max,50%(median),25%,missing_count,min,mean,0
0,APARTMENTS_AVG,0.10824,0.1485,2339,151450,NaN,float64,1,0.0876,0.0577,156061,0,0.11744,0.006304
1,APARTMENTS_MEDI,0.109076,0.1489,1148,151450,NaN,float64,1,0.0864,0.0583,156061,0,0.11785,0.007340
2,APARTMENTS_MODE,0.107936,0.1439,760,151450,NaN,float64,1,0.084,0.0525,156061,0,0.114231,0.018693
3,BASEMENTAREA_AVG,0.0824382,0.1122,3780,127568,NaN,float64,1,0.0763,0.0442,179943,0,0.0884422,0.000177
4,BASEMENTAREA_MEDI,0.0821787,0.1116,3772,127568,NaN,float64,1,0.0758,0.0437,179943,0,0.0879549,0.009327
5,BASEMENTAREA_MODE,0.0843072,0.1124,3841,127568,NaN,float64,1,0.0746,0.0407,179943,0,0.0875432,0.022446
6,COMMONAREA_AVG,0.0760357,0.0515,3181,92646,NaN,float64,1,0.0211,0.0078,214865,0,0.0446207,0.014726
7,COMMONAREA_MEDI,0.0761443,0.0513,3202,92646,NaN,float64,1,0.0208,0.0079,214865,0,0.0445951,0.013220
8,COMMONAREA_MODE,0.0744445,0.049,3128,92646,NaN,float64,1,0.019,0.0072,214865,0,0.0425531,0.005010
9,ELEVATORS_AVG,0.134576,0.12,257,143620,NaN,float64,1,0,0,163891,0,0.0789415,0.034154
10,ELEVATORS_MEDI,0.134467,0.12,46,143620,NaN,float64,1,0,0,163891,0,0.0780778,0.027272
11,ELEVATORS_MODE,0.132256,0.1208,26,143620,NaN,float64,1,0,0,163891,0,0.0744897,0.012438
12,ENTRANCES_AVG,0.100049,0.2069,285,152683,NaN,float64,1,0.1379,0.069,154828,0,0.149725,0.008173
13,ENTRANCES_MEDI,0.100368,0.2069,46,152683,NaN,float64,1,0.1379,0.069,154828,0,0.149213,0.011602
14,ENTRANCES_MODE,0.100977,0.2069,30,152683,NaN,float64,1,0.1379,0.069,154828,0,0.145193,0.019798
15,FLAG_CONT_MOBILE,0.0431639,1,2,307511,NaN,int64,1,1,1,0,0,0.998133,0.030867
16,FLAG_DOCUMENT_10,0.00477106,0,2,307511,NaN,int64,1,0,0,0,0,2.27634e-05,NaN
17,FLAG_DOCUMENT_11,0.0624241,0,2,307511,NaN,int64,1,0,0,0,0,0.00391206,0.011410
18,FLAG_DOCUMENT_12,0.00255026,0,2,307511,NaN,int64,1,0,0,0,0,6.50383e-06,NaN
19,FLAG_DOCUMENT_13,0.0592677,0,2,307511,NaN,int64,1,0,0,0,0,0.00352508,0.000314
20,FLAG_DOCUMENT_14,0.0541098,0,2,307511,NaN,int64,1,0,0,0,0,0.00293648,0.038411
21,FLAG_DOCUMENT_15,0.0347599,0,2,307511,NaN,int64,1,0,0,0,0,0.00120971,0.026183
22,FLAG_DOCUMENT_16,0.0991442,0,2,307511,NaN,int64,1,0,0,0,0,0.0099281,0.034356
23,FLAG_DOCUMENT_17,0.0163275,0,2,307511,NaN,int64,1,0,0,0,0,0.000266657,0.020431
24,FLAG_DOCUMENT_18,0.0897982,0,2,307511,NaN,int64,1,0,0,0,0,0.00812979,0.005754
25,FLAG_DOCUMENT_19,0.0243875,0,2,307511,NaN,int64,1,0,0,0,0,0.000595101,0.014036
26,FLAG_DOCUMENT_2,0.00650179,0,2,307511,NaN,int64,1,0,0,0,0,4.22749e-05,NaN
27,FLAG_DOCUMENT_20,0.0225176,0,2,307511,NaN,int64,1,0,0,0,0,0.000507299,0.008819
28,FLAG_DOCUMENT_21,0.0182985,0,2,307511,NaN,int64,1,0,0,0,0,0.000334947,0.017949
29,FLAG_DOCUMENT_3,0.453752,1,2,307511,NaN,int64,1,1,0,0,0,0.710023,0.035044
30,FLAG_DOCUMENT_4,0.00901618,0,2,307511,NaN,int64,1,0,0,0,0,8.12979e-05,0.006719
31,FLAG_DOCUMENT_5,0.12201,0,2,307511,NaN,int64,1,0,0,0,0,0.0151149,0.016921
32,FLAG_DOCUMENT_6,0.283376,0,2,307511,NaN,int64,1,0,0,0,0,0.0880554,0.002310
33,FLAG_DOCUMENT_7,0.0138502,0,2,307511,NaN,int64,1,0,0,0,0,0.000191863,0.012296
34,FLAG_DOCUMENT_8,0.273412,0,2,307511,NaN,int64,1,0,0,0,0,0.081376,0.006132
35,FLAG_DOCUMENT_9,0.0622947,0,2,307511,NaN,int64,1,0,0,0,0,0.0038958,0.045541
36,FLAG_EMAIL,0.231307,0,2,307511,NaN,int64,1,0,0,0,0,0.0567199,0.014237
37,FLAG_EMP_PHONE,0.38428,1,2,307511,NaN,int64,1,1,1,0,0,0.819889,0.007901
38,FLAG_MOBIL,0.00180331,1,2,307511,NaN,int64,1,1,1,0,0,0.999997,NaN
39,FLAG_PHONE,0.449521,1,2,307511,NaN,int64,1,0,0,0,0,0.281066,0.031663
40,FLAG_WORK_PHONE,0.399526,0,2,307511,NaN,int64,1,0,0,0,0,0.199368,0.040041
41,FLOORSMAX_AVG,0.144641,0.3333,403,154491,NaN,float64,1,0.1667,0.1667,153020,0,0.226282,0.018492
42,FLOORSMAX_MEDI,0.145067,0.3333,49,154491,NaN,float64,1,0.1667,0.1667,153020,0,0.225897,0.013408
43,FLOORSMAX_MODE,0.143709,0.3333,25,154491,NaN,float64,1,0.1667,0.1667,153020,0,0.222315,0.006052
44,FLOORSMIN_AVG,0.16138,0.375,305,98869,NaN,float64,1,0.2083,0.0833,208642,0,0.231894,0.012405
45,FLOORSMIN_MEDI,0.161934,0.375,47,98869,NaN,float64,1,0.2083,0.0833,208642,0,0.231625,0.013085
46,FLOORSMIN_MODE,0.16116,0.375,25,98869,NaN,float64,1,0.2083,0.0833,208642,0,0.228058,0.026440
47,LANDAREA_AVG,0.0811836,0.0856,3527,124921,NaN,float64,1,0.0481,0.0187,182590,0,0.0663332,0.029735
48,LANDAREA_MEDI,0.082167,0.0868,3560,124921,NaN,float64,1,0.0487,0.0187,182590,0,0.0671687,0.024180
49,LANDAREA_MODE,0.0817503,0.0841,3563,124921,NaN,float64,1,0.0458,0.0166,182590,0,0.0649577,0.023178
50,LIVE_CITY_NOT_WORK_CITY,0.383817,0,2,307511,NaN,int64,1,0,0,0,0,0.179555,0.005797
51,LIVE_REGION_NOT_WORK_REGION,0.197499,0,2,307511,NaN,int64,1,0,0,0,0,0.0406587,0.011873
52,LIVINGAPARTMENTS_AVG,0.0925761,0.121,1868,97312,NaN,float64,1,0.0756,0.0504,210199,0,0.100775,0.014553
53,LIVINGAPARTMENTS_MEDI,0.0936423,0.1231,1097,97312,NaN,float64,1,0.0761,0.0513,210199,0,0.101954,0.028143
54,LIVINGAPARTMENTS_MODE,0.0978804,0.1313,736,97312,NaN,float64,1,0.0771,0.0542,210199,0,0.105645,0.030688
55,LIVINGAREA_AVG,0.110565,0.1299,5199,153161,NaN,float64,1,0.0745,0.0453,154350,0,0.107399,0.024921
56,LIVINGAREA_MEDI,0.11226,0.1303,5281,153161,NaN,float64,1,0.0749,0.0457,154350,0,0.108607,0.015470
57,LIVINGAREA_MODE,0.111845,0.1252,5301,153161,NaN,float64,1,0.0731,0.0427,154350,0,0.105975,0.006039
58,NONLIVINGAPARTMENTS_AVG,0.0477317,0.0039,386,93997,NaN,float64,1,0,0,213514,0,0.00880867,0.004322
59,NONLIVINGAPARTMENTS_MEDI,0.0474147,0.0039,214,93997,NaN,float64,1,0,0,213514,0,0.00865101,0.004989
60,NONLIVINGAPARTMENTS_MODE,0.0462763,0.0039,167,93997,NaN,float64,1,0,0,213514,0,0.00807639,0.008848
61,NONLIVINGAREA_AVG,0.0695232,0.0277,3290,137829,NaN,float64,1,0.0036,0,169682,0,0.0283578,0.007723
62,NONLIVINGAREA_MEDI,0.0701665,0.0266,3323,137829,NaN,float64,1,0.0031,0,169682,0,0.0282359,0.007194
63,NONLIVINGAREA_MODE,0.0702539,0.0231,3327,137829,NaN,float64,1,0.0011,0,169682,0,0.0270223,0.022117
64,REG_CITY_NOT_LIVE_CITY,0.268444,0,2,307511,NaN,int64,1,0,0,0,0,0.0781728,0.054274
65,REG_CITY_NOT_WORK_CITY,0.421124,0,2,307511,NaN,int64,1,0,0,0,0,0.230454,0.011753
66,REG_REGION_NOT_LIVE_REGION,0.122126,0,2,307511,NaN,int64,1,0,0,0,0,0.0151442,0.009819
67,REG_REGION_NOT_WORK_REGION,0.219526,0,2,307511,NaN,int64,1,0,0,0,0,0.0507689,0.003820
68,TARGET,0.272419,0,2,307511,NaN,int64,1,0,0,0,0,0.0807288,NaN
69,TOTALAREA_MODE,0.107462,0.1276,5116,159080,NaN,float64,1,0.0688,0.0412,148431,0,0.102547,0.048464
70,YEARS_BEGINEXPLUATATION_AVG,0.0592233,0.9866,285,157504,NaN,float64,1,0.9816,0.9767,150007,0,0.977735,0.021360
71,YEARS_BEGINEXPLUATATION_MEDI,0.0598973,0.9866,245,157504,NaN,float64,1,0.9816,0.9767,150007,0,0.977752,0.029857
72,YEARS_BEGINEXPLUATATION_MODE,0.0645754,0.9866,221,157504,NaN,float64,1,0.9816,0.9767,150007,0,0.977065,0.019506
73,YEARS_BUILD_AVG,0.11328,0.8232,149,103023,NaN,float64,1,0.7552,0.6872,204488,0,0.752471,0.013055
74,YEARS_BUILD_MEDI,0.112066,0.8256,151,103023,NaN,float64,1,0.7585,0.6914,204488,0,0.755746,0.013371
75,YEARS_BUILD_MODE,0.110111,0.8236,154,103023,NaN,float64,1,0.7648,0.6994,204488,0,0.759637,0.000430

In [150]:
application_train[~application_train['SK_ID_CURR'].isin(indexList)].groupby(['TARGET'])['AMT_REQ_CREDIT_BUREAU_QRT'].mean()

TARGET
0    0.264876
1    0.259923
Name: AMT_REQ_CREDIT_BUREAU_QRT, dtype: float64

In [229]:
application_train.groupby(['TARGET'])['DAYS_EMPLOYED'].mean()

TARGET
0    65696.146123
1    42394.675448
Name: DAYS_EMPLOYED, dtype: float64

In [251]:
tmp3.head()

   TARGET  DAYS_EMPLOYED
0  1       6.458338
1  0       7.080868
2  0       5.420535
3  0       8.019613
4  0       8.019284

In [293]:
feat='DAYS_ID_PUBLISH'
tmp3=application_train[['TARGET', feat]]
tmp3[feat]=np.log(np.abs(tmp3[feat])+1)
fig = PlotlyVisualization.createHistPlotForVarForBinaryClass2(tmp3, 'TARGET', feat, 'No Loan Issue', 'Loan Issue',feat)
# fig = PlotlyVisualization.createHistPlotForVarForBinaryClass2(application_train[['TARGET', feat]], 'TARGET', feat, 'No Loan Issue', 'Loan Issue',feat)
py.iplot(fig, filename='overlaid histogram')

C:\Users\vberlia\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\vberlia\AppData\Local\Continuum\Anaconda3\lib\site-packages\plotly\plotly\plotly.py:224: UserWarning:

Woah there! Look at all those points! Due to browser limitations, the Plotly SVG drawing functions have a hard time graphing more than 500k data points for line charts, or 40k points for other types of charts. Here are some suggestions:
(1) Use the `plotly.graph_objs.Scattergl` trace object to generate a WebGl graph.
(2) Trying using the image API to return an image instead of a graph URL
(3) Use matplotlib
(4) See if you can create your visualization with fewer data points

If the visualization you're using aggregates points (e.g., box plot, histogram, etc.) you can disregard this warning.

In [295]:
feat='EXT_SOURCE_3'
fig = PlotlyVisualization.createHistPlotForVarForBinaryClass2(application_train[~application_train['SK_ID_CURR'].isin(indexList)][['TARGET', feat]], 'TARGET', feat, 'No Loan Issue', 'Loan Issue',feat)
py.iplot(fig, filename='overlaid histogram')

C:\Users\vberlia\AppData\Local\Continuum\Anaconda3\lib\site-packages\plotly\plotly\plotly.py:224: UserWarning:

Woah there! Look at all those points! Due to browser limitations, the Plotly SVG drawing functions have a hard time graphing more than 500k data points for line charts, or 40k points for other types of charts. Here are some suggestions:
(1) Use the `plotly.graph_objs.Scattergl` trace object to generate a WebGl graph.
(2) Trying using the image API to return an image instead of a graph URL
(3) Use matplotlib
(4) See if you can create your visualization with fewer data points

If the visualization you're using aggregates points (e.g., box plot, histogram, etc.) you can disregard this warning.

In [296]:
feat_weights

                                    feat_name         0
0    EXT_SOURCE_3                              0.342958
1    EXT_SOURCE_2                              0.255334
2    EXT_SOURCE_1                              0.114284
3    EXT_SOURCE_1_is_missing                   0.075403
4    AMT_GOODS_PRICE                           0.073957
5    AMT_ANNUITY                               0.069739
6    REGION_POPULATION_RELATIVE                0.063206
7    DAYS_ID_PUBLISH                           0.061460
8    NAME_EDUCATION_TYPE_freq                  0.059415
9    occupation_type_secretaries               0.058782
10   OWN_CAR_AGE                               0.058301
11   DEF_60_CNT_SOCIAL_CIRCLE                  0.057516
12   occupation_type_medicine_staff            0.054533
13   REG_CITY_NOT_LIVE_CITY                    0.054274
14   NAME_INCOME_TYPE_freq                     0.050247
15   AMT_REQ_CREDIT_BUREAU_DAY                 0.050193
16   AMT_REQ_CREDIT_BUREAU_QRT                 0.048834
17   organization_type_industry:_type_12       0.048580
18   TOTALAREA_MODE                            0.048464
19   organization_type_bank                    0.047909
20   organization_type_medicine                0.047420
21   occupation_type_security_staff            0.047215
22   occupation_type_sales_staff               0.046844
23   FLAG_DOCUMENT_9_freq                      0.045541
24   FLAG_DOCUMENT_9                           0.045541
25   organization_type_trade:_type_6           0.045521
26   AMT_REQ_CREDIT_BUREAU_MON                 0.045423
27   DEF_30_CNT_SOCIAL_CIRCLE                  0.044119
28   HOUR_APPR_PROCESS_START                   0.043575
29   occupation_type_low-skill_laborers        0.040720
30   AMT_REQ_CREDIT_BUREAU_WEEK                0.040497
31   FLAG_WORK_PHONE_freq                      0.040041
32   FLAG_WORK_PHONE                           0.040041
33   DAYS_REGISTRATION                         0.038710
34   REGION_RATING_CLIENT_freq                 0.038593
35   FLAG_DOCUMENT_14                          0.038411
36   FLAG_DOCUMENT_14_freq                     0.038411
37   occupation_type_accountants               0.038201
38   organization_type_industry:_type_4        0.037830
39   organization_type_industry:_type_1        0.037542
40   FLAG_DOCUMENT_3                           0.035044
41   FLAG_DOCUMENT_3_freq                      0.035044
42   AMT_GOODS_PRICE_is_missing                0.034926
43   FLAG_DOCUMENT_16                          0.034356
44   FLAG_DOCUMENT_16_freq                     0.034356
45   code_gender_f                             0.034352
46   CODE_GENDER_freq                          0.034352
47   code_gender_m                             0.034352
48   ELEVATORS_AVG                             0.034154
49   organization_type_telecom                 0.032930
50   organization_type_industry:_type_2        0.032306
51   ORGANIZATION_TYPE_freq                    0.032235
52   FLAG_PHONE                                0.031663
53   FLAG_PHONE_freq                           0.031663
54   FLAG_CONT_MOBILE_freq                     0.030867
55   FLAG_CONT_MOBILE                          0.030867
56   LIVINGAPARTMENTS_MODE                     0.030688
57   YEARS_BEGINEXPLUATATION_MEDI              0.029857
58   LANDAREA_AVG                              0.029735
59   occupation_type_core_staff                0.029224
60   organization_type_trade:_type_1           0.028715
61   LIVINGAPARTMENTS_MEDI                     0.028143
62   organization_type_industry:_type_13       0.027897
63   organization_type_legal_services          0.027819
64   ELEVATORS_MEDI                            0.027272
65   ELEVATORS_MODE_is_missing                 0.027221
66   ELEVATORS_MEDI_is_missing                 0.027221
67   ELEVATORS_AVG_is_missing                  0.027221
68   name_contract_type_revolving_loans        0.027136
69   name_contract_type_cash_loans             0.027136
70   NAME_CONTRACT_TYPE_freq                   0.027136
71   FLOORSMIN_MODE                            0.026440
72   FLAG_DOCUMENT_15_freq                     0.026183
73   FLAG_DOCUMENT_15                          0.026183
74   occupation_type_managers                  0.026161
75   organization_type_trade:_type_3           0.025942
76   organization_type_restaurant              0.025848
77   CNT_CHILDREN                              0.025629
78   organization_type_realtor                 0.025438
79   organization_type_kindergarten            0.025351
80   NAME_FAMILY_STATUS_freq                   0.024998
81   LIVINGAREA_AVG                            0.024921
82   LANDAREA_MEDI                             0.024180
83   OBS_60_CNT_SOCIAL_CIRCLE                  0.023856
84   organization_type_self-employed           0.023482
85   LANDAREA_MODE                             0.023178
86   OBS_30_CNT_SOCIAL_CIRCLE                  0.022671
87   BASEMENTAREA_MODE                         0.022446
88   organization_type_government              0.022441
89   organization_type_hotel                   0.022367
90   NONLIVINGAREA_MODE                        0.022117
91   organization_type_industry:_type_6        0.021458
92   NAME_HOUSING_TYPE_freq                    0.021411
93   YEARS_BEGINEXPLUATATION_AVG               0.021360
94   organization_type_transport:_type_4       0.021213
95   occupation_type_cooking_staff             0.020995
96   organization_type_business_entity_type_3  0.020841
97   organization_type_transport:_type_1       0.020784
98   COMMONAREA_AVG_is_missing                 0.020714
99   COMMONAREA_MEDI_is_missing                0.020714
100  COMMONAREA_MODE_is_missing                0.020714
101  FLAG_DOCUMENT_17                          0.020431
102  FLAG_DOCUMENT_17_freq                     0.020431
103  organization_type_industry:_type_11       0.020390
104  organization_type_industry:_type_9        0.020058
105  organization_type_housing                 0.019948
106  ENTRANCES_MODE                            0.019798
107  organization_type_industry:_type_3        0.019759
108  AMT_INCOME_TOTAL                          0.019546
109  YEARS_BEGINEXPLUATATION_MODE              0.019506
110  DAYS_LAST_PHONE_CHANGE                    0.019349
111  organization_type_religion                0.018733
112  LIVINGAPARTMENTS_MODE_is_missing          0.018733
113  LIVINGAPARTMENTS_MEDI_is_missing          0.018733
114  LIVINGAPARTMENTS_AVG_is_missing           0.018733
115  APARTMENTS_MODE                           0.018693
116  occupation_type_high_skill_tech_staff     0.018563
117  FLOORSMAX_AVG                             0.018492
118  FLAG_DOCUMENT_21_freq                     0.017949
119  FLAG_DOCUMENT_21                          0.017949
120  organization_type_trade:_type_4           0.017477
121  DAYS_BIRTH                                0.016928
122  FLAG_DOCUMENT_5                           0.016921
123  FLAG_DOCUMENT_5_freq                      0.016921
124  BASEMENTAREA_AVG_is_missing               0.016796
125  BASEMENTAREA_MODE_is_missing              0.016796
126  BASEMENTAREA_MEDI_is_missing              0.016796
127  WEEKDAY_APPR_PROCESS_START_freq           0.016763
128  organization_type_transport:_type_3       0.016589
129  occupation_type_it_staff                  0.016514
130  organization_type_military                0.016473
131  flag_own_car_n                            0.016268
132  OWN_CAR_AGE_is_missing                    0.016268
133  flag_own_car_y                            0.016268
134  FLAG_OWN_CAR_freq                         0.016268
135  occupation_type_realty_agents             0.016134
136  LIVINGAREA_MEDI                           0.015470
137  organization_type_trade:_type_7           0.014962
138  EXT_SOURCE_3_is_missing                   0.014794
139  COMMONAREA_AVG                            0.014726
140  organization_type_industry:_type_10       0.014715
141  LIVINGAPARTMENTS_AVG                      0.014553
142  REGION_RATING_CLIENT_W_CITY_freq          0.014330
143  TOTALAREA_MODE_is_missing                 0.014319
144  FLAG_EMAIL_freq                           0.014237
145  FLAG_EMAIL                                0.014237
146  FLAG_DOCUMENT_19_freq                     0.014036
147  FLAG_DOCUMENT_19                          0.014036
148  organization_type_business_entity_type_1  0.013527
149  FLOORSMAX_MEDI                            0.013408
150  YEARS_BUILD_MEDI                          0.013371
151  COMMONAREA_MEDI                           0.013220
152  DAYS_EMPLOYED                             0.013145
153  FLOORSMIN_MEDI                            0.013085
154  YEARS_BUILD_AVG                           0.013055
155  organization_type_security_ministries     0.012884
156  AMT_REQ_CREDIT_BUREAU_HOUR                0.012540
157  organization_type_police                  0.012534
158  organization_type_electricity             0.012527
159  organization_type_other                   0.012509
160  ELEVATORS_MODE                            0.012438
161  FLOORSMIN_AVG                             0.012405
162  organization_type_emergency               0.012314
163  FLAG_DOCUMENT_7                           0.012296
164  FLAG_DOCUMENT_7_freq                      0.012296
165  AMT_REQ_CREDIT_BUREAU_YEAR                0.012086
166  AMT_REQ_CREDIT_BUREAU_YEAR_is_missing     0.011933
167  AMT_REQ_CREDIT_BUREAU_HOUR_is_missing     0.011933
168  AMT_REQ_CREDIT_BUREAU_QRT_is_missing      0.011933
169  AMT_REQ_CREDIT_BUREAU_MON_is_missing      0.011933
170  AMT_REQ_CREDIT_BUREAU_DAY_is_missing      0.011933
171  AMT_REQ_CREDIT_BUREAU_WEEK_is_missing     0.011933
172  LIVE_REGION_NOT_WORK_REGION               0.011873
173  LIVE_REGION_NOT_WORK_REGION_freq          0.011873
174  REG_CITY_NOT_WORK_CITY_freq               0.011753
175  REG_CITY_NOT_WORK_CITY                    0.011753
176  organization_type_trade:_type_5           0.011741
177  ENTRANCES_MEDI                            0.011602
178  occupation_type_laborers                  0.011450
179  FLAG_DOCUMENT_11_freq                     0.011410
180  FLAG_DOCUMENT_11                          0.011410
181  organization_type_trade:_type_2           0.010913
182  organization_type_security                0.010876
183  organization_type_university              0.010395
184  organization_type_culture                 0.010247
185  organization_type_advertising             0.009951
186  REG_REGION_NOT_LIVE_REGION                0.009819
187  REG_REGION_NOT_LIVE_REGION_freq           0.009819
188  ENTRANCES_MODE_is_missing                 0.009746
189  ENTRANCES_MEDI_is_missing                 0.009746
190  ENTRANCES_AVG_is_missing                  0.009746
191  LIVINGAREA_MODE_is_missing                0.009640
192  LIVINGAREA_AVG_is_missing                 0.009640
193  LIVINGAREA_MEDI_is_missing                0.009640
194  organization_type_services                0.009570
195  BASEMENTAREA_MEDI                         0.009327
196  organization_type_postal                  0.008959
197  NONLIVINGAPARTMENTS_MODE                  0.008848
198  FLAG_DOCUMENT_20_freq                     0.008819
199  FLAG_DOCUMENT_20                          0.008819
200  CNT_CHILDREN_freq                         0.008398
201  occupation_type_hr_staff                  0.008372
202  occupation_type_cleaning_staff            0.008370
203  ENTRANCES_AVG                             0.008173
204  organization_type_xna                     0.007901
205  FLAG_EMP_PHONE_freq                       0.007901
206  FLAG_EMP_PHONE                            0.007901
207  NONLIVINGAREA_AVG                         0.007723
208  organization_type_business_entity_type_2  0.007658
209  NONLIVINGAPARTMENTS_MEDI_is_missing       0.007568
210  NONLIVINGAPARTMENTS_MODE_is_missing       0.007568
211  NONLIVINGAPARTMENTS_AVG_is_missing        0.007568
212  APARTMENTS_MEDI                           0.007340
213  NONLIVINGAREA_MEDI                        0.007194
214  FLAG_DOCUMENT_4_freq                      0.006719
215  FLAG_DOCUMENT_4                           0.006719
216  FLOORSMIN_AVG_is_missing                  0.006563
217  FLOORSMIN_MODE_is_missing                 0.006563
218  FLOORSMIN_MEDI_is_missing                 0.006563
219  organization_type_mobile                  0.006411
220  APARTMENTS_AVG                            0.006304
221  organization_type_industry:_type_5        0.006294
222  FLAG_DOCUMENT_8                           0.006132
223  FLAG_DOCUMENT_8_freq                      0.006132
224  NONLIVINGAREA_MODE_is_missing             0.006116
225  NONLIVINGAREA_AVG_is_missing              0.006116
226  NONLIVINGAREA_MEDI_is_missing             0.006116
227  FLOORSMAX_MODE                            0.006052
228  LIVINGAREA_MODE                           0.006039
229  LIVE_CITY_NOT_WORK_CITY_freq              0.005797
230  LIVE_CITY_NOT_WORK_CITY                   0.005797
231  FLAG_DOCUMENT_18                          0.005754
232  FLAG_DOCUMENT_18_freq                     0.005754
233  EXT_SOURCE_2_is_missing                   0.005438
234  occupation_type_drivers                   0.005377
235  organization_type_agriculture             0.005322
236  COMMONAREA_MODE                           0.005010
237  NONLIVINGAPARTMENTS_MEDI                  0.004989
238  occupation_type_waiters/barmen_staff      0.004933
239  organization_type_construction            0.004416
240  NONLIVINGAPARTMENTS_AVG                   0.004322
241  flag_own_realty_n                         0.004034
242  flag_own_realty_y                         0.004034
243  FLAG_OWN_REALTY_freq                      0.004034
244  REG_REGION_NOT_WORK_REGION_freq           0.003820
245  REG_REGION_NOT_WORK_REGION                0.003820
246  YEARS_BEGINEXPLUATATION_AVG_is_missing    0.003386
247  YEARS_BEGINEXPLUATATION_MEDI_is_missing   0.003386
248  YEARS_BEGINEXPLUATATION_MODE_is_missing   0.003386
249  organization_type_cleaning                0.003352
250  LANDAREA_AVG_is_missing                   0.002735
251  LANDAREA_MODE_is_missing                  0.002735
252  LANDAREA_MEDI_is_missing                  0.002735
253  OBS_30_CNT_SOCIAL_CIRCLE_is_missing       0.002603
254  DEF_30_CNT_SOCIAL_CIRCLE_is_missing       0.002603
255  DEF_60_CNT_SOCIAL_CIRCLE_is_missing       0.002603
256  OBS_60_CNT_SOCIAL_CIRCLE_is_missing       0.002603
257  occupation_type_private_service_staff     0.002415
258  organization_type_insurance               0.002321
259  FLAG_DOCUMENT_6                           0.002310
260  FLAG_DOCUMENT_6_freq                      0.002310
261  YEARS_BUILD_MEDI_is_missing               0.002098
262  YEARS_BUILD_AVG_is_missing                0.002098
263  YEARS_BUILD_MODE_is_missing               0.002098
264  organization_type_transport:_type_2       0.001774
265  APARTMENTS_AVG_is_missing                 0.001481
266  APARTMENTS_MEDI_is_missing                0.001481
267  APARTMENTS_MODE_is_missing                0.001481
268  CNT_FAM_MEMBERS                           0.001148
269  organization_type_school                  0.000882
270  AMT_CREDIT                                0.000864
271  YEARS_BUILD_MODE                          0.000430
272  organization_type_industry:_type_7        0.000372
273  FLAG_DOCUMENT_13_freq                     0.000314
274  FLAG_DOCUMENT_13                          0.000314
275  FLOORSMAX_MEDI_is_missing                 0.000193
276  FLOORSMAX_MODE_is_missing                 0.000193
277  FLOORSMAX_AVG_is_missing                  0.000193
278  BASEMENTAREA_AVG                          0.000177
279  REG_CITY_NOT_WORK_CITY_is_missing         0.000000
280  REGION_POPULATION_RELATIVE_is_missing     0.000000
281  FLAG_DOCUMENT_11_is_missing               0.000000
282  FLAG_DOCUMENT_9_is_missing                0.000000
283  FLAG_DOCUMENT_3_is_missing                0.000000
284  FLAG_DOCUMENT_10_freq                     0.000000
285  DAYS_ID_PUBLISH_is_missing                0.000000
286  FLAG_DOCUMENT_7_is_missing                0.000000
287  REG_CITY_NOT_LIVE_CITY_is_missing         0.000000
288  FLAG_DOCUMENT_13_is_missing               0.000000
289  FLAG_WORK_PHONE_is_missing                0.000000
290  CNT_FAM_MEMBERS_is_missing                0.000000
291  AMT_ANNUITY_is_missing                    0.000000
292  CNT_CHILDREN_is_missing                   0.000000
293  REG_REGION_NOT_LIVE_REGION_is_missing     0.000000
294  FLAG_PHONE_is_missing                     0.000000
295  FLAG_EMAIL_is_missing                     0.000000
296  FLAG_DOCUMENT_14_is_missing               0.000000
297  FLAG_DOCUMENT_19_is_missing               0.000000
298  FLAG_DOCUMENT_15_is_missing               0.000000
299  FLAG_DOCUMENT_17_is_missing               0.000000
300  FLAG_DOCUMENT_12_freq                     0.000000
301  FLAG_DOCUMENT_2_freq                      0.000000
302  FLAG_MOBIL_freq                           0.000000
303  FLAG_DOCUMENT_20_is_missing               0.000000
304  DAYS_LAST_PHONE_CHANGE_is_missing         0.000000
305  AMT_INCOME_TOTAL_is_missing               0.000000
306  AMT_CREDIT_is_missing                     0.000000
307  DAYS_REGISTRATION_is_missing              0.000000
308  FLAG_DOCUMENT_4_is_missing                0.000000
309  FLAG_DOCUMENT_5_is_missing                0.000000
310  DAYS_BIRTH_is_missing                     0.000000
311  FLAG_DOCUMENT_6_is_missing                0.000000
312  FLAG_CONT_MOBILE_is_missing               0.000000
313  LIVE_REGION_NOT_WORK_REGION_is_missing    0.000000
314  REG_REGION_NOT_WORK_REGION_is_missing     0.000000
315  LIVE_CITY_NOT_WORK_CITY_is_missing        0.000000
316  FLAG_DOCUMENT_21_is_missing               0.000000
317  FLAG_DOCUMENT_18_is_missing               0.000000
318  FLAG_EMP_PHONE_is_missing                 0.000000
319  FLAG_DOCUMENT_16_is_missing               0.000000
320  DAYS_EMPLOYED_is_missing                  0.000000
321  FLAG_DOCUMENT_8_is_missing                0.000000
322  HOUR_APPR_PROCESS_START_is_missing        0.000000

In [223]:
# Extreme Outliers
indexList=[]
indexList.extend(list(application_train[application_train['AMT_REQ_CREDIT_BUREAU_QRT']==261].SK_ID_CURR))
indexList.extend(list(application_train[application_train['OBS_30_CNT_SOCIAL_CIRCLE']>=24].SK_ID_CURR))
indexList.extend(list(application_train[application_train['AMT_REQ_CREDIT_BUREAU_DAY']>=2].SK_ID_CURR))
indexList.extend(list(application_train[application_train['AMT_REQ_CREDIT_BUREAU_HOUR']>=3].SK_ID_CURR))
indexList=list(set(indexList))

In [219]:
len(list(application_train[application_train['AMT_REQ_CREDIT_BUREAU_YEAR']>=3].SK_ID_CURR))

80594

In [297]:
tmp_removal = ['EMERGENCYSTATE_MODE',
               'FONDKAPREMONT_MODE',
               'HOUSETYPE_MODE',
               'NAME_TYPE_SUITE',
               'OCCUPATION_TYPE',
               'WALLSMATERIAL_MODE','TARGET']

In [301]:
one_hot_columns = ['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR',
               'FLAG_OWN_REALTY', 'OCCUPATION_TYPE', 'ORGANIZATION_TYPE'
               ]

In [308]:
summT.transpose()[tmp_removal]

,EMERGENCYSTATE_MODE,FONDKAPREMONT_MODE,HOUSETYPE_MODE,NAME_TYPE_SUITE,OCCUPATION_TYPE,WALLSMATERIAL_MODE
std,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN
count_unique,2,4,3,7,18,7
count,NaN,NaN,NaN,NaN,NaN,NaN
mode,No,reg oper account,block of flats,Unaccompanied,Laborers,Panel
col_type,object,object,object,object,object,object
max,NaN,NaN,NaN,NaN,NaN,NaN
50%(median),NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN
missing_count,145755,210295,154297,1292,96391,156341
min,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN

In [303]:
application_train[one_hot_columns].head()

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,OCCUPATION_TYPE,ORGANIZATION_TYPE
0,Cash loans,M,N,Y,Laborers,Business Entity Type 3
1,Cash loans,F,N,N,Core staff,School
2,Revolving loans,M,Y,Y,Laborers,Government
3,Cash loans,F,N,Y,Laborers,Business Entity Type 3
4,Cash loans,M,N,Y,Core staff,Religion

In [300]:
DataSummary.returnFrequencyCounts(application_train[tmp_removal],['EMERGENCYSTATE_MODE',
                   'FONDKAPREMONT_MODE',
                   'HOUSETYPE_MODE',
                   'NAME_TYPE_SUITE',
                   'OCCUPATION_TYPE',
                   'WALLSMATERIAL_MODE'])

{'EMERGENCYSTATE_MODE':   EMERGENCYSTATE_MODE   count
 0  No                  159428
 1  Yes                 2328  ,
 'FONDKAPREMONT_MODE':       FONDKAPREMONT_MODE  count
 0  reg oper account       73830
 1  reg oper spec account  12080
 2  not specified          5687
 3  org spec account       5619 ,
 'HOUSETYPE_MODE':      HOUSETYPE_MODE   count
 0  block of flats    150503
 1  specific housing  1499
 2  terraced house    1212  ,
 'NAME_TYPE_SUITE':    NAME_TYPE_SUITE   count
 0  Unaccompanied    248526
 1  Family           40149
 2  Spouse, partner  11370
 3  Children         3267
 4  Other_B          1770
 5  Other_A          866
 6  Group of people  271   ,
 'OCCUPATION_TYPE':           OCCUPATION_TYPE  count
 0   Laborers               55186
 1   Sales staff            32102
 2   Core staff             27570
 3   Managers               21371
 4   Drivers                18603
 5   High skill tech staff  11380
 6   Accountants            9813
 7   Medicine staff         8537
 8   Security staff         6721
 9   Cooking staff          5946
 10  Cleaning staff         4653
 11  Private service staff  2652
 12  Low-skill Laborers     2093
 13  Waiters/barmen staff   1348
 14  Secretaries            1305
 15  Realty agents          751
 16  HR staff               563
 17  IT staff               526  ,
 'WALLSMATERIAL_MODE':   WALLSMATERIAL_MODE  count
 0  Panel              66040
 1  Stone, brick       64815
 2  Block              9253
 3  Wooden             5362
 4  Mixed              2296
 5  Monolithic         1779
 6  Others             1625 }

In [200]:
list(application_train[application_train['AMT_REQ_CREDIT_BUREAU_HOUR']>=3].SK_ID_CURR)

[131850,
 133522,
 164710,
 183567,
 206116,
 227725,
 278383,
 279420,
 317202,
 402308]

In [125]:
tmp=summT.transpose()[list(set(application_train.columns)-set(tmp.feat_name))].transpose()
tmp.insert(0,'feat_name',tmp.index)
tmp=pd.merge(tmp,feat_weights,on='feat_name',how='left')
# tmp=pd.merge(tmp,desc,on='feat_name',how='left')
tmp

,feat_name,std,75%,count_unique,count,mode,col_type,max,50%(median),25%,missing_count,min,mean,0
0,DAYS_LAST_PHONE_CHANGE,826.808,-274,3773,307510,NaN,float64,0,-757,-1570,1,-4292,-962.859,0.019349
1,AMT_REQ_CREDIT_BUREAU_QRT,0.794056,0,11,265992,NaN,float64,261,0,0,41519,0,0.265474,0.048834
2,OBS_30_CNT_SOCIAL_CIRCLE,2.40099,2,33,306490,NaN,float64,348,0,0,1021,0,1.42225,0.022671
3,OBS_60_CNT_SOCIAL_CIRCLE,2.3798,2,33,306490,NaN,float64,344,0,0,1021,0,1.40529,0.023856
4,CODE_GENDER,NaN,NaN,3,NaN,F,object,NaN,NaN,NaN,0,NaN,NaN,NaN
5,WEEKDAY_APPR_PROCESS_START,NaN,NaN,7,NaN,TUESDAY,object,NaN,NaN,NaN,0,NaN,NaN,NaN
6,CNT_FAM_MEMBERS,0.910682,3,17,307509,NaN,float64,20,2,2,2,1,2.15267,0.001148
7,HOUR_APPR_PROCESS_START,3.26583,14,24,307511,NaN,int64,23,12,10,0,0,12.0634,0.043575
8,FLAG_OWN_REALTY,NaN,NaN,2,NaN,Y,object,NaN,NaN,NaN,0,NaN,NaN,NaN
9,EXT_SOURCE_1,0.211062,0.675053,114584,134133,NaN,float64,0.962693,0.505998,0.334007,173378,0.0145681,0.50213,0.114284
10,ORGANIZATION_TYPE,NaN,NaN,58,NaN,Business Entity Type 3,object,NaN,NaN,NaN,0,NaN,NaN,NaN
11,DAYS_REGISTRATION,3522.89,-2010,15688,307511,NaN,float64,0,-4504,-7479.5,0,-24672,-4986.12,0.038710
12,NAME_FAMILY_STATUS,NaN,NaN,6,NaN,Married,object,NaN,NaN,NaN,0,NaN,NaN,NaN
13,AMT_REQ_CREDIT_BUREAU_DAY,0.110757,0,9,265992,NaN,float64,9,0,0,41519,0,0.00700021,0.050193
14,AMT_REQ_CREDIT_BUREAU_HOUR,0.0838491,0,5,265992,NaN,float64,4,0,0,41519,0,0.00640245,0.012540
15,DEF_60_CNT_SOCIAL_CIRCLE,0.362291,0,9,306490,NaN,float64,24,0,0,1021,0,0.100049,0.057516
16,AMT_REQ_CREDIT_BUREAU_YEAR,1.86929,3,25,265992,NaN,float64,25,1,0,41519,0,1.89997,0.012086
17,REGION_RATING_CLIENT_W_CITY,0.502737,2,3,307511,NaN,int64,3,2,2,0,1,2.03152,NaN
18,REGION_RATING_CLIENT,0.509034,2,3,307511,NaN,int64,3,2,2,0,1,2.05246,NaN
19,NAME_CONTRACT_TYPE,NaN,NaN,2,NaN,Cash loans,object,NaN,NaN,NaN,0,NaN,NaN,NaN
20,DAYS_EMPLOYED,141276,-289,12574,307511,NaN,int64,365243,-1213,-2760,0,-17912,63815,0.013145
21,OWN_CAR_AGE,11.9448,15,62,104582,NaN,float64,91,9,5,202929,0,12.0611,0.058301
22,FONDKAPREMONT_MODE,NaN,NaN,4,NaN,reg oper account,object,NaN,NaN,NaN,210295,NaN,NaN,NaN
23,WALLSMATERIAL_MODE,NaN,NaN,7,NaN,Panel,object,NaN,NaN,NaN,156341,NaN,NaN,NaN
24,AMT_ANNUITY,14493.7,34596,13672,307499,NaN,float64,258026,24903,16524,12,1615.5,27108.6,0.069739
25,AMT_REQ_CREDIT_BUREAU_WEEK,0.204685,0,9,265992,NaN,float64,8,0,0,41519,0,0.0343619,0.040497
26,AMT_INCOME_TOTAL,237123,202500,2548,307511,NaN,float64,1.17e+08,147150,112500,0,25650,168798,0.019546
27,HOUSETYPE_MODE,NaN,NaN,3,NaN,block of flats,object,NaN,NaN,NaN,154297,NaN,NaN,NaN
28,AMT_REQ_CREDIT_BUREAU_MON,0.916002,0,24,265992,NaN,float64,27,0,0,41519,0,0.267395,0.045423
29,AMT_CREDIT,402491,808650,5603,307511,NaN,float64,4.05e+06,513531,270000,0,45000,599026,0.000864
30,EXT_SOURCE_2,0.19106,0.663617,119831,306851,NaN,float64,0.855,0.565961,0.392457,660,8.17362e-08,0.514393,0.255334
31,REGION_POPULATION_RELATIVE,0.0138313,0.028663,81,307511,NaN,float64,0.072508,0.01885,0.010006,0,0.00029,0.0208681,0.063206
32,NAME_INCOME_TYPE,NaN,NaN,8,NaN,Working,object,NaN,NaN,NaN,0,NaN,NaN,NaN
33,EMERGENCYSTATE_MODE,NaN,NaN,2,NaN,No,object,NaN,NaN,NaN,145755,NaN,NaN,NaN
34,SK_ID_CURR,102790,367142,307511,307511,NaN,int64,456255,278202,189146,0,100002,278181,NaN
35,AMT_GOODS_PRICE,369446,679500,1002,307233,NaN,float64,4.05e+06,450000,238500,278,40500,538396,0.073957
36,DEF_30_CNT_SOCIAL_CIRCLE,0.446698,0,10,306490,NaN,float64,34,0,0,1021,0,0.143421,0.044119
37,DAYS_BIRTH,4363.99,-12413,17460,307511,NaN,int64,-7489,-15750,-19682,0,-25229,-16037,0.016928
38,DAYS_ID_PUBLISH,1509.45,-1720,6168,307511,NaN,int64,0,-3254,-4299,0,-7197,-2994.2,0.061460
39,CNT_CHILDREN,0.722121,1,15,307511,NaN,int64,19,0,0,0,0,0.417052,0.025629
40,NAME_EDUCATION_TYPE,NaN,NaN,5,NaN,Secondary / secondary special,object,NaN,NaN,NaN,0,NaN,NaN,NaN
41,EXT_SOURCE_3,0.194844,0.669057,814,246546,NaN,float64,0.89601,0.535276,0.37065,60965,0.000527265,0.510853,0.342958
42,NAME_HOUSING_TYPE,NaN,NaN,6,NaN,House / apartment,object,NaN,NaN,NaN,0,NaN,NaN,NaN
43,FLAG_OWN_CAR,NaN,NaN,2,NaN,N,object,NaN,NaN,NaN,0,NaN,NaN,NaN
44,OCCUPATION_TYPE,NaN,NaN,18,NaN,Laborers,object,NaN,NaN,NaN,96391,NaN,NaN,NaN
45,NAME_TYPE_SUITE,NaN,NaN,7,NaN,Unaccompanied,object,NaN,NaN,NaN,1292,NaN,NaN,NaN

In [111]:
tmp=summT[]
tmp.insert(0,'feat_name',tmp.index)
# tmp=pd.merge(tmp,feat_weights,on='feat_name',how='left')
# tmp=pd.merge(tmp,desc,on='feat_name',how='left')
tmp.shape

(33, 13)

In [101]:
home_credit_col_desc

,Unnamed: 0,Table,Row,Description,Special
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN
1,2,application_{train|test}.csv,TARGET,"Target variable (1 - client with payment difficulties: he/she had late payment more than X days on at least one of the first Y installments of the loan in our sample, 0 - all other cases)",NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN
5,8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN
6,9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN
7,10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN
8,11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN
9,12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN
10,13,application_{train|test}.csv,AMT_GOODS_PRICE,For consumer loans it is the price of the goods for which the loan is given,NaN
11,14,application_{train|test}.csv,NAME_TYPE_SUITE,Who was accompanying client when he was applying for the loan,NaN
12,15,application_{train|test}.csv,NAME_INCOME_TYPE,"Clients income type (businessman, working, maternity leave, )",NaN
13,16,application_{train|test}.csv,NAME_EDUCATION_TYPE,Level of highest education the client achieved,NaN
14,17,application_{train|test}.csv,NAME_FAMILY_STATUS,Family status of the client,NaN
15,18,application_{train|test}.csv,NAME_HOUSING_TYPE,"What is the housing situation of the client (renting, living with parents, ...)",NaN
16,19,application_{train|test}.csv,REGION_POPULATION_RELATIVE,Normalized population of region where client lives (higher number means the client lives in more populated region),normalized
17,20,application_{train|test}.csv,DAYS_BIRTH,Client's age in days at the time of application,time only relative to the application
18,21,application_{train|test}.csv,DAYS_EMPLOYED,How many days before the application the person started current employment,time only relative to the application
19,22,application_{train|test}.csv,DAYS_REGISTRATION,How many days before the application did client change his registration,time only relative to the application
20,23,application_{train|test}.csv,DAYS_ID_PUBLISH,How many days before the application did client change the identity document with which he applied for the loan,time only relative to the application
21,24,application_{train|test}.csv,OWN_CAR_AGE,Age of client's car,NaN
22,25,application_{train|test}.csv,FLAG_MOBIL,"Did client provide mobile phone (1=YES, 0=NO)",NaN
23,26,application_{train|test}.csv,FLAG_EMP_PHONE,"Did client provide work phone (1=YES, 0=NO)",NaN
24,27,application_{train|test}.csv,FLAG_WORK_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN
25,28,application_{train|test}.csv,FLAG_CONT_MOBILE,"Was mobile phone reachable (1=YES, 0=NO)",NaN
26,29,application_{train|test}.csv,FLAG_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN
27,30,application_{train|test}.csv,FLAG_EMAIL,"Did client provide email (1=YES, 0=NO)",NaN
28,31,application_{train|test}.csv,OCCUPATION_TYPE,What kind of occupation does the client have,NaN
29,32,application_{train|test}.csv,CNT_FAM_MEMBERS,How many family members does client have,NaN
30,33,application_{train|test}.csv,REGION_RATING_CLIENT,"Our rating of the region where client lives (1,2,3)",NaN
31,34,application_{train|test}.csv,REGION_RATING_CLIENT_W_CITY,"Our rating of the region where client lives with taking city into account (1,2,3)",NaN
32,35,application_{train|test}.csv,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply for the loan,NaN
33,36,application_{train|test}.csv,HOUR_APPR_PROCESS_START,Approximately at what hour did the client apply for the loan,rounded
34,37,application_{train|test}.csv,REG_REGION_NOT_LIVE_REGION,"Flag if client's permanent address does not match contact address (1=different, 0=same, at region level)",NaN
35,38,application_{train|test}.csv,REG_REGION_NOT_WORK_REGION,"Flag if client's permanent address does not match work address (1=different, 0=same, at region level)",NaN
36,39,application_{train|test}.csv,LIVE_REGION_NOT_WORK_REGION,"Flag if client's contact address does not match work address (1=different, 0=same, at region level)",NaN
37,40,application_{train|test}.csv,REG_CITY_NOT_LIVE_CITY,"Flag if client's permanent address does not match contact address (1=different, 0=same, at city level)",NaN
38,41,application_{train|test}.csv,REG_CITY_NOT_WORK_CITY,"Flag if client's permanent address does not match work address (1=different, 0=same, at city level)",NaN
39,42,application_{train|test}.csv,LIVE_CITY_NOT_WORK_CITY,"Flag if client's contact address does not match work address (1=different, 0=same, at city level)",NaN
40,43,application_{train|test}.csv,ORGANIZATION_TYPE,Type of organization where client works,NaN
41,44,application_{train|test}.csv,EXT_SOURCE_1,Normalized score from external data source,normalized
42,45,application_{train|test}.csv,EXT_SOURCE_2,Normalized score from external data source,normalized
43,46,application_{train|test}.csv,EXT_SOURCE_3,Normalized score from external data source,normalized
44,47,application_{train|test}.csv,APARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
45,48,application_{train|test}.csv,BASEMENTAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
46,49,application_{train|test}.csv,YEARS_BEGINEXPLUATATION_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
47,50,application_{train|test}.csv,YEARS_BUILD_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
48,51,application_{train|test}.csv,COMMONAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
49,52,application_{train|test}.csv,ELEVATORS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
50,53,application_{train|test}.csv,ENTRANCES_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
51,54,application_{train|test}.csv,FLOORSMAX_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
52,55,application_{train|test}.csv,FLOORSMIN_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
53,56,application_{train|test}.csv,LANDAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
54,57,application_{train|test}.csv,LIVINGAPARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
55,58,application_{train|test}.csv,LIVINGAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
56,59,application_{train|test}.csv,NONLIVINGAPARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
57,60,application_{train|test}.csv,NONLIVINGAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
58,61,application_{train|test}.csv,APARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
59,62,application_{train|test}.csv,BASEMENTAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
60,63,application_{train|test}.csv,YEARS_BEGINEXPLUATATION_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
61,64,application_{train|test}.csv,YEARS_BUILD_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
62,65,application_{train|test}.csv,COMMONAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
63,66,application_{train|test}.csv,ELEVATORS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
64,67,application_{train|test}.csv,ENTRANCES_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
65,68,application_{train|test}.csv,FLOORSMAX_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
66,69,application_{train|test}.csv,FLOORSMIN_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
67,70,application_{train|test}.csv,LANDAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
68,71,application_{train|test}.csv,LIVINGAPARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
69,72,application_{train|test}.csv,LIVINGAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
70,73,application_{train|test}.csv,NONLIVINGAPARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
71,74,application_{train|test}.csv,NONLIVINGAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
72,75,application_{train|test}.csv,APARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
73,76,application_{train|test}.csv,BASEMENTAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
74,77,application_{train|test}.csv,YEARS_BEGINEXPLUATATION_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
75,78,application_{train|test}.csv,YEARS_BUILD_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
76,79,application_{train|test}.csv,COMMONAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
77,80,application_{train|test}.csv,ELEVATORS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
78,81,application_{train|test}.csv,ENTRANCES_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
79,82,application_{train|test}.csv,FLOORSMAX_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
80,83,application_{train|test}.csv,FLOORSMIN_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
81,84,application_{train|test}.csv,LANDAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
82,85,application_{train|test}.csv,LIVINGAPARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
83,86,application_{train|test}.csv,LIVINGAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
84,87,application_{train|test}.csv,NONLIVINGAPARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
85,88,application_{train|test}.csv,NONLIVINGAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

In [102]:
a=['TARGET',
   'FLAG_OWN_REALTY',
    'APARTMENTS_AVG',
 'APARTMENTS_MEDI',
 'APARTMENTS_MODE',
 'BASEMENTAREA_AVG',
 'BASEMENTAREA_MEDI',
 'BASEMENTAREA_MODE',
 'COMMONAREA_AVG',
 'COMMONAREA_MEDI',
 'COMMONAREA_MODE',
 'ELEVATORS_AVG',
 'ELEVATORS_MEDI',
 'ELEVATORS_MODE',
 'ENTRANCES_AVG',
 'ENTRANCES_MEDI',
 'ENTRANCES_MODE',
 'FLOORSMAX_AVG',
 'FLOORSMAX_MEDI',
 'FLOORSMAX_MODE',
 'FLOORSMIN_AVG',
 'FLOORSMIN_MEDI',
 'FLOORSMIN_MODE',
 'LANDAREA_AVG',
 'LANDAREA_MEDI',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_AVG',
 'LIVINGAREA_MEDI',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_AVG',
 'NONLIVINGAREA_MEDI',
 'NONLIVINGAREA_MODE',
 'TOTALAREA_MODE',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_AVG',
 'YEARS_BUILD_MEDI',
 'YEARS_BUILD_MODE']

In [103]:
tmp2=application_train[a]

In [104]:
tmp2.head()

,TARGET,FLAG_OWN_REALTY,APARTMENTS_AVG,APARTMENTS_MEDI,APARTMENTS_MODE,BASEMENTAREA_AVG,BASEMENTAREA_MEDI,BASEMENTAREA_MODE,COMMONAREA_AVG,COMMONAREA_MEDI,COMMONAREA_MODE,ELEVATORS_AVG,ELEVATORS_MEDI,ELEVATORS_MODE,ENTRANCES_AVG,ENTRANCES_MEDI,ENTRANCES_MODE,FLOORSMAX_AVG,FLOORSMAX_MEDI,FLOORSMAX_MODE,FLOORSMIN_AVG,FLOORSMIN_MEDI,FLOORSMIN_MODE,LANDAREA_AVG,LANDAREA_MEDI,LANDAREA_MODE,LIVINGAPARTMENTS_AVG,LIVINGAPARTMENTS_MEDI,LIVINGAPARTMENTS_MODE,LIVINGAREA_AVG,LIVINGAREA_MEDI,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_AVG,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_AVG,NONLIVINGAREA_MEDI,NONLIVINGAREA_MODE,TOTALAREA_MODE,YEARS_BEGINEXPLUATATION_AVG,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_AVG,YEARS_BUILD_MEDI,YEARS_BUILD_MODE
0,1,Y,0.0247,0.0250,0.0252,0.0369,0.0369,0.0383,0.0143,0.0144,0.0144,0.00,0.00,0.0000,0.0690,0.0690,0.0690,0.0833,0.0833,0.0833,0.1250,0.1250,0.1250,0.0369,0.0375,0.0377,0.0202,0.0205,0.022,0.0190,0.0193,0.0198,0.0000,0.0000,0.0,0.0000,0.00,0.0,0.0149,0.9722,0.9722,0.9722,0.6192,0.6243,0.6341
1,0,N,0.0959,0.0968,0.0924,0.0529,0.0529,0.0538,0.0605,0.0608,0.0497,0.08,0.08,0.0806,0.0345,0.0345,0.0345,0.2917,0.2917,0.2917,0.3333,0.3333,0.3333,0.0130,0.0132,0.0128,0.0773,0.0787,0.079,0.0549,0.0558,0.0554,0.0039,0.0039,0.0,0.0098,0.01,0.0,0.0714,0.9851,0.9851,0.9851,0.7960,0.7987,0.8040
2,0,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
application_train.groupby(['TARGET'])['AMT_GOODS_PRICE'].mean()

TARGET
0    542736.795003
1    488972.412554
Name: AMT_GOODS_PRICE, dtype: float64

In [100]:
DataSummary.returnFrequencyCounts(tmp2,['TARGET'])

{'TARGET':    TARGET   count
 0  0       282686
 1  1       24825 }

In [108]:
tmp3=tmp2[tmp2['APARTMENTS_AVG'].isnull()]
DataSummary.returnFrequencyCounts(tmp3[tmp3['FLAG_OWN_REALTY']=='N'],['TARGET'])

{'TARGET':    TARGET  count
 0  0       44737
 1  1       4640 }

In [51]:
application_train[list(set(application_train.columns)-set(a.index))].head()

,EMERGENCYSTATE_MODE,FONDKAPREMONT_MODE,WALLSMATERIAL_MODE,HOUSETYPE_MODE,OCCUPATION_TYPE,NAME_TYPE_SUITE
0,No,reg oper account,"Stone, brick",block of flats,Laborers,Unaccompanied
1,No,reg oper account,Block,block of flats,Core staff,Family
2,NaN,NaN,NaN,NaN,Laborers,Unaccompanied
3,NaN,NaN,NaN,NaN,Laborers,Unaccompanied
4,NaN,NaN,NaN,NaN,Core staff,Unaccompanied

In [ ]:
train_sample=application_train.sample(10000,random_state=0)
train_sample=train_sample.reset_index()
original_index=train_sample['index']
train_sample=train_sample.drop('index',axis=1)

X=train_sample.values
Y=train_sample['TARGET']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.10, random_state=42)
X_train=pd.DataFrame(X_train)
X_train.columns=train_sample.columns
X_test=pd.DataFrame(X_test)
X_test.columns=train_sample.columns